### ISSUE TITLE
Internal version tracking system broken for plugins

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#10]
The internal file revision tracking system within CBRAIN, used for provenance methods, has two modes of operation.

1. it interacts with GIT to find its information if the system was deployed with GIT
2. if GIT isn't installed or CBRAIN wasn't installed with a `git clone` command, as a fallback it fetches its information from a text flatfile in the installation's root directory

However, now that tasks and userfiles are distributed as separate plugins, the version information is no longer present in the flatfile, so mode 2 doesn't work anymore

I'm not sure how to solve that.

**Comment by prioux** [comment]
Mode 1 (with GIT) works perfectly. For the fallback method, we need a flatfile in each plugin package, maybe.

**Comment by crocodoyle** [comment]
Fixed by #461, can be closed

**Comment by prioux** [comment]
Indeed.
