### ISSUE TITLE
Neurohub documentation display error (Firefox only)

### ISSUE THREAD

**Issue by AlexandreHutton** [aces/cbrain#1009]
Trying to open the UKBB lists on the [documentation page](https://neurohub.ca/documentation.html) (under 3.b) results in an unscrollable box a few pixels wide:
![Screenshot from 2020-09-09 18-21-25](https://user-images.githubusercontent.com/50920802/92661232-2b2e6d80-f2ca-11ea-8dd3-240edc588170.png)

The issue occurs with Firefox 80.0.1 (64-bit), but doesn't occur with Chromium.

**Comment by prioux** [comment]
@AlexandreHutton Closed thsi issue and recreated it in https://github.com/aces/cbrain-website/issues/6

**Comment by 3design** [comment]
the documentation page has been moved to the github wiki. the documentation.html page is left on the repo for the purpose of an archive however if this is confusing, I can remove the html page so that it is no longer available. Anyone have thoughts about this?

**Comment by prioux** [comment]
@3design I suggest you ask this in the other isssue, not here in cbrain:

https://github.com/neurohub/neurohub.github.io/issues/18

Even though the original screenshot is here, this repo is mostly about the cbrain codebase
