### ISSUE TITLE
Login and Dashboard page - adjust spellings of Neurohub to NeuroHub

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#1017]
Minor comment that appears to be cosmetic but should be resolved so as to ensure consistency, and demonstrate attention to detail.

Please update spellings on the portal pages that write 'Neurohub' to instead be 'NeuroHub'.

Examples of pages like this include:

https://portal.neurohub.ca/signin

https://portal.neurohub.ca/neurohub

Thanks.

**Comment by prioux** [comment]
Fixed by #1021
