### ISSUE TITLE
Change request - Portal banner menu to include link to 'Documentation'

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#1018]
Presently NeuroHub has a front-facing page that links to the Portal and to the Documentation.  This front-facing page is different than the Portal of course, but I have concern that the Documentation isn't as readily accessible to users as it can be as a reference point, much like their 'Projects' and 'Storage' which are on the top of the page.

Can a 'Documentation' item be aded to the portal banner menu of items along side the others?

This would also be a helpful reference during all phases of testing and day-to-day use.

https://github.com/neurohub/neurohub_documentation/wiki
![Screen Shot 2020-09-22 at 1 42 27 PM](https://user-images.githubusercontent.com/65622686/93918459-61141e80-fcda-11ea-9324-e042da6e8b31.png)

**Comment by prioux** [comment]
Sure, it's easy. I suggest putting it on the right side between `My Account` and `Logout`.

**Comment by prioux** [comment]
I suggest @MontrealSergiy can do this maybe?

**Comment by bryancaron** [comment]
Any update @MontrealSergiy ? Thanks.

**Comment by prioux** [comment]
Closed by #1023
