### ISSUE TITLE
Formalize a little the specifications for overlay files in tool config.

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1026]
Following #1016, a tool config now has a text area where the admin can configure overlays. The current syntax supports three specification types:

```
/path/to/file.squashfs
dp:1234
dp:name_of_dp
```

I'd like to make this better looking and more formal.

I suggest we change the spec so that files are described with FILE URIs, and we can also specify overlays directly registered in CBRAIN too. Also, support embedded comments.

```
# A file located on the cluster
file:/path/to/file.squashfs
# All overlays configured for DP 1234
dp:1234
# My special overlay in CBRAIN
userfile:1234
```

We'll need to extract the parser into a more proper stand-alone method (right now we just plsit on whitespace and commas)

**Comment by prioux** [comment]
The last example, `userfile:1234` will require the set-up code to perform a `sync_to_cache()` on the userfile found by ID, and the to use `cache_full_path` to get the path that will go into the singularity command as an overlay.

**Comment by MontrealSergiy** [comment]
@prioux not sure what such a simple language needs a proper parser? What so bad with splitting on whitespace? Any use beside the comments (which can be just added to split's regex)? Do you want support filenames with space inside? Around semicolon? Or it is some irrelevant to overlay DSL style thing?
