### ISSUE TITLE
eliminate codebase and test suits dependency on plugins

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1032]
CBrain should be usable with any set of plugings. However codebase and unittest depend on presence of certain plugins (e.g. TextFile). Would it be better to put most necessary plugins in the repo or create separate plugins test suits? Not sure how feasible that though.

**Comment by natacha-beck** [comment]
@MontrealSergiy the TextFile plugins and some other are included in CBRAIN code base directly (in cbrain-plugins-base): 
--> https://github.com/aces/cbrain/tree/master/BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles 
So I don't think we create external dependence.

**Comment by prioux** [comment]
Yes, cbrain-plugins-base is a built-in plugin. It cannot be distributed separately either, because it contains some core models used throughout the platform (e.g. SingleFile, FileCollection).
