### ISSUE TITLE
Add editable 'News' section for the dashboard

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1043]
This is for both CBRAIN and NeuroHub. Let the admin customize and record one (or several?) news items in the dashboard.

Not sure where to store the info though. CBRAIN has a built-in `help_button()` helper which stores the text in a file on the filesystem, so maybe use this mechanism with an option such that it shows in page instead as a separate help panel.

**Comment by MontrealSergiy** [comment]
Alternatively could be a message (send by admin or everybody... ) .  
If needed can be varying visibility or individually targeted news.

Bonus is internal links are supported out of box.

If needed is a good idea enable HTML or lightweight markup ( bbcode / markdown ...) support or text is fine?

I have seen cases other roles than admin where allowed to post news. (may be site manager?) Are existing news editable? Is draft mode/preview needed?

**Comment by prioux** [comment]
There are many possibilities, let's talk about it out loud before any code is written.
