### ISSUE TITLE
File Upload - default storage

### ISSUE THREAD

**Issue by adora07** [aces/cbrain#1046]
We received some feedback that depending on the experience of a user, it is not always obvious which storage configuration should be selected during file upload. 

At minimum, is it possible to indicate which option is the "default" storage option?

<img width="1047" alt="Screen Shot 2020-10-23 at 1 42 38 PM" src="https://user-images.githubusercontent.com/44646677/97036679-29e19900-1536-11eb-9516-23721b5b6e0e.png">

**Comment by prioux** [comment]
Can you tell me in private which user said that? Normally all users have a default set for them. It's part of the account creation process.

**Comment by prioux** [comment]
Six users created during the month of September were not given a default. Fixing now.
