### ISSUE TITLE
Creating a CbrainFileList sometimes assign it to a project that the user should not be able to write to.

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1055]
The code simply uses:

```ruby
current_project.id
```

that's too general.

Also: check all instances of such code? (including `current_project.try(:id)`)

**Comment by prioux** [comment]
This is a consequence of NeuroHub, by the way, That bug wasn't possible before.

**Comment by MontrealSergiy** [comment]
@prioux also new task and file registration try to assign to the current project. Fix within this issue?

**Comment by prioux** [comment]
Yes, good thinking.

Try to make sure the code use the proper `_ids` methods we have defined (assignable_group_ids etc) if possible/relevant.
