### ISSUE TITLE
Replace the logic that computes a main revision number with 'git describe --tags' instead

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1066]
We have two places in the code where a bunch of Ruby statements issues a bunch of git commands to come up with a live revision number for the system.

One of these places is in BrainPortal/script/show_cbrain_rev ; when run it returns something like "6.0.0-123"

There exists a git command that pretty much does the same thing in a much quicker and efficient way: `git describe --tags` ; the output contains a commit ID that will need to be stripped out.

Replace the code in show_cbrain_rev with a single call to `git describe --tags` ; the other place where a similar operation is performed is in file BrainPortal/lib/cbrain_file_revision.rb starting at line 405 (approximately), in method cbrain_head_tag.

Do not change any of the other logic in the code, JUST the way to compute that string.

**Comment by prioux** [comment]
Estimated time: 2 hours.

**Comment by MontrealSergiy** [comment]
what's with `-z` flag (defaulting) ? drop it/just ignore inside of show_cbrain_rev/keep as is?

in bash will be

```git describe --tags | sed 's/\(.*\)-.*/\1/'```

**Comment by prioux** [comment]
Just don't change the script's logic

Your sed statement is buggy if there are no commits after the tag. Think about it.

**Comment by MontrealSergiy** [comment]
What kind of bug for directly tagged you found? Regretfully cannot figure it out

**Comment by prioux** [comment]
The thing you're trying to remove is on the right side  of the string, so use a right anchor in the regex.

```
git tag -a -m dummy 9.0-alpha
git describe --tags
9.0-alpha
git describe --tags | sed 's/\(.*\)-.*/\1/'
9.0
git tag -d 9.0-alpha
```

**Comment by MontrealSergiy** [comment]
To cover hyphens I would rather go for 

```git describe --long --tags |  sed 's/\(.*\)-.*/\1/'``` 

Hex matching like

```sed 's/\(.*\)-g[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]/\1/'``` 

might cover most Greek letters, yet longer than above and somebody can put a hex looking number like 7-ge0202101

**Comment by MontrealSergiy** [comment]
If you wish can use ruby instead of sed, yet it is already used.

**Comment by prioux** [comment]
I've seen the logic in that commit; please do the string post processing on the ruby side, not the shell side. You get a much better regex engine in ruby than in sed, and you won't have to fork several processes and establish a fifo between them.

**Comment by prioux** [comment]
And remember to handle the case prolery when thecbrian codebase is not deployed using git.

**Comment by prioux** [comment]
There is not a PR for this?

**Comment by MontrealSergiy** [comment]
Will submit. Have strange behavior for users deploying without git, but those must be minority
