### ISSUE TITLE
The persistent selection mechanism is broken

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1071]
The link 'select all' when you have several pages of userfiles no longer selects all the files on all pages. In fact it seems to not select anything for real.

Tested on both Firefox and Chrome. I suspect something changed in the browser APIs. The firefox console logs errors about access to the persistent selection database. On the server side I verified and the controller code properly returns a list of all IDs when a GET to `/userfiles?only_ids=1` is performed by the JS code in the browser.

**Comment by prioux** [comment]
It works perfectly fine in Safari by the way.

**Comment by natacha-beck** [comment]
Works fine on chrome and firefox, on my side on Ubuntu even in incognito mode.

**Comment by natacha-beck** [comment]
Never mind it seems to work but it doesn´t.

**Comment by MontrealSergiy** [comment]
Last year indeed there were few changes in chrome/firefox local storage api, I hear the sync and quotes https://chromium.googlesource.com/chromium/src/+blame/refs/heads/master/storage/browser/quota/quota_settings.cc there are of course some minor changes, syncing, yet they lead to data loss only at concurrent conflicting requests I think https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/

**Comment by MontrealSergiy** [comment]
The bug shows on my Safari btw

![image](https://user-images.githubusercontent.com/11949081/105368695-cbc56000-5bcf-11eb-88df-4a941db0713e.png)

**Comment by MontrealSergiy** [comment]
@prioux while I observe problems, especially on Chrome, I am wondering what exactly you meant 'it seems to not select anything for real'. On my Chrome 'select all' seem select all files, at the least count them, though I cannot count all _my_ files .

**Comment by prioux** [comment]
The screenshot above is a symptom of the other issue, #1072 

This issue was about not being able to select all files on all pages, and I can't reproduce it. So I will close this. All further discussions about the persistent selection mechanism should go to issue #1072 or the associated PR, #1073
