### ISSUE TITLE
The persistent selection mechnism doesn't respect the "own files vs all available files" state

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1072]
In the file manager, users can toggle between "see only my files" vs "see all available files".

If the "select all files" link is pressed, and the user is in "see only my files" mode, the files selected will still be all the available files.

See screenshot, which has all the numbers (a filter is applied on the DP, and there are 131530 files on that DP, though only 125 belong to the user):

![Screen Shot 2021-01-04 at 14 35 56](https://user-images.githubusercontent.com/777588/103572449-9532da00-4e9a-11eb-8a50-39502e376e35.png)

Discovered on Safari because in Chrome and Firefox issue #1071 is still active.

**Comment by MontrealSergiy** [comment]
Not sure it is related one thing I hear the quotes for storage changed https://chromium.googlesource.com/chromium/src/+blame/refs/heads/master/storage/browser/quota/quota_settings.cc

**Comment by MontrealSergiy** [comment]
@natacha-beck Just curious do you observe the same bug you described in Safari, if so what version?
