### ISSUE TITLE
Creation of CBCSV file can be store in public project that is not assignable.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#1081]
When a user has a Public project selected, he can select multiple files to create a CBCSV file. In this case, the file will be registered in the Public project even if the project is not assignable. 

I think that the CBCSV file should be registered under the personal User Project.

**Comment by prioux** [comment]
I'm assigning this to @MontrealSergiy  with high priority.It should be really easy to fix.

**Comment by prioux** [comment]
This is a duplicate of #1055

**Comment by prioux** [comment]
Tracking to be performed in #1055
