### ISSUE TITLE
The 'export as CSV' feature generates bad CSV output

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1082]
The file manager has a 'export as csv' feature. The output is inconsistent, with some strings quoted and some not:

```csv
Diagnostics-BiancaExec-21171-1.txt,8055,TextFile,admin,"admin","2019-10-07 11:49:13 EDT","2019-10-07 11:49:15 EDT","BrowsableBianca","",""
Diagnostics-BiancaExec-21170-1.txt,8369,TextFile,admin,"admin","2019-10-03 15:35:05 EDT","2019-10-09 15:58:13 EDT","SmartBianca","",""
Diagnostics-PriouxGraPlat-21165-1.txt,26406,TextFile,admin,"admin","2019-09-17 22:10:32 EDT","2019-11-20 16:43:51 EST","SmartBianca","Work,QC_PASS,QC_FAIL",""
blah,14219,SingleFile,admin,"admin","2019-09-17 16:26:01 EDT","2019-09-17 16:26:02 EDT","SmartBianca","",""
```

**Comment by MontrealSergiy** [comment]
csv format allows both quoted and unquoted data, string or not. Typically quotations can help if there are commas inside the string, quotation insides the string then have to be escaped with double quota. The quotations are mandatory for strings with line-break, double-quote or commas  https://tools.ietf.org/html/rfc4180 . What concers the present format I suspend the developer desired to quote fields that might contains spaces or commas for greater readability. Do you think correction still needed? If so, you would prefer to quote just all the strings?

**Comment by prioux** [comment]
Yes, make it systematically proper, even if the spec is loose.
