### ISSUE TITLE
The master_select boxes in the browse provider page no longer work

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1087]
We have two master select boxes at the top of the data provider browse page:

```
Register files as [file_select], and directories as [directory_select]
```

These master select boxes are supposed to switch all the other select boxes down the page automatically when the user picks a type in them. using a "on change" event.

The master select boxes no longer do that. The other selection boxes are not changed.

Estimated time: one day.

**Comment by MontrealSergiy** [comment]
yup, apparently with chosen, additional event to be triggered

> Updating Chosen Dynamically
> If you need to update the options in your select field and want Chosen to pick up the changes, you'll need to trigger the "chosen:updated" event on the field. Chosen will re-build itself based on the updated content.
> 
> $("#form_field").trigger("chosen:updated");

**Comment by MontrealSergiy** [comment]
looks like it's broken again

**Comment by natacha-beck** [comment]
@MontrealSergiy Can you test it again. Works fine on my end.

**Comment by MontrealSergiy** [comment]
did you test the second page or just the first?

**Comment by MontrealSergiy** [comment]
works now closing
