### ISSUE TITLE
Data Provider Type Information link rendering defects

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1093]
To reproduce:
1. Click data providers
2. Click Create New
3. As new Data Provider form opens find (Data Provider Type Information) link and click it

Observed: The the text of info is not always readable due to interference with other form fields
Expected: All text can be read

Tested with Chrome Version 88.0.4324.150 (Official Build) (64-bit) Win 10

Not a priority as info target admin who anyways mostly already know  what is data provider (unless there similar links with regular user pages)
![image](https://user-images.githubusercontent.com/11949081/107882499-b46c5080-6eb7-11eb-95dc-839c51465d59.png)

**Comment by prioux** [comment]
It's prob just the z-index. Fix it it should take one minute at most.

**Comment by MontrealSergiy** [comment]
![image](https://user-images.githubusercontent.com/11949081/108105470-a86cc400-705a-11eb-97c3-b5a201c041b1.png)

**Comment by MontrealSergiy** [comment]
you mean just to prioritize that info box over dropdows? Yup hides dropdowns
```
--- a/BrainPortal/app/assets/stylesheets/cbrain.css.erb
+++ b/BrainPortal/app/assets/stylesheets/cbrain.css.erb
@@ -2277,6 +2277,7 @@ img {
 /* % ######################################################### */

 #data_provider_classes {
+  z-index: 1100;
   max-width: 60em;
   position: absolute;
```
