### ISSUE TITLE
 Use gem 'sys-proctable' in ScirUnix class (redmine 569)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#110]
The sys-proctable module (or gem) is useful and
should be used as a platform-independent way to access
the list of processes on the system. Anton's next
revision of the worker framework already uses it,
but I found another place where it could be
used: the scir_unix.rb file.

**Comment by crocodoyle** [comment]
There is no scir_local.rb file any more

**Comment by prioux** [comment]
It's a mistake in the description; it's suppose to be `scir_unix.rb`

**Comment by prioux** [comment]
We've been using `ps x -o pid,uid,state` for 10 years now (since Oct 2009, commit https://github.com/aces/cbrain/commit/d79d976d2d1be36dfecf28589155e46dfd887e7c !) and it works fine on both Linux and MacOS, so let's close this.
