### ISSUE TITLE
Create a new userfile action with direct routing to file collection elements.

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1107]
It would be nice to have a new route for getting dirrect access to file collection's elements, no matter how deep, directly from the URL (and not from a query parameters). Something like:

GET /userfiles/12345/files/abcd/efgh/hello.txt

which would stream the file abcd/efgh/hello.txt out of file collection 12345.

We need to agree on the action prefix (here /userfiles/1234/files) and whether or not we include the name of the file collection itself as a first component.

This would make it easy to  write new viewers for file collections that have embedded HTML documents that have relative paths to assets within the collection.

E.g. FMRIPrep outputs contain HTML file reports.

**Comment by natacha-beck** [comment]
The TractoFlow output will (maybe) require the same kind of feature. It have HTML, CSS and JS inside the output directory.

**Comment by prioux** [comment]
Ah. Looks like this was already created a few years ago. The action is `file_collection_content`. It's in commit 847f2458

**Comment by Najmahan** [comment]
Almost all pipelines that deal with 4D images have an html "view result" page. It's like our CIVET's verify which is created with CIVET-QC and I think to design into this 'viewing' an option for the user to set a QC flag would be fantastic.

**Comment by prioux** [comment]
This is already done and operational; we added a `stream` action that has a better default content disposition than the old `file_collection_content` in #1114
