### ISSUE TITLE
Update of NeuroHub logo image on portal login page

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#1112]
Hi, As mentioned in the meeting of April 28, the NeuroHub logo that is to be uniformly used is the one containing the HBHL acronym.  The logo present on the portal.neurohub.ca page uses the full name of Healthy Brains, Healthy Lives.

Can this please be updated to the new logo?  From what I can see, this should be the only instance of the logo in use that needs changing.  The new logo is linked from the meeting notes. Thanks.

Best regards,

Bryan.

**Comment by MontrealSergiy** [comment]
@prioux @natacha-beck Hi, Pierre should I work on that?

**Comment by MontrealSergiy** [comment]
@bryancaron Hi, I submitted a version for review, yet I used the same logo as in all other neurohub portal pages (for greater uniformity), yet I just realize, that all portal logos are different from the new one: one on neurohub.ca has smaller HBHL font and bigger NEUROHUB, than. So should I keep old  font sizes or do you prefer

1) change all the logo occurences on portal to new logo?
2) change all the logos on login page?
3) replace left logo with the new one, delete the logo on right
3) change only the originally mentioned logo spelled out in left upper corner

![image](https://user-images.githubusercontent.com/11949081/116901972-908fef80-ac08-11eb-8978-8c1bae182cf1.png)

**Comment by MontrealSergiy** [comment]
Above is the current version, and option 4 would look like 

![image](https://user-images.githubusercontent.com/11949081/116902619-5a9f3b00-ac09-11eb-8cfa-268c27beb679.png)
