### ISSUE TITLE
Multiple tasks are launched if many files are selected.

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1127]
This one may be a feature. If several files in file explorer are selected (but only one is used), several tasks, one for each file is launched. 

It might be actually a useful feature, as relieves user from creating CBRAIN File lists, but a bit unexpected. IMHO a warning might be appropriate.

**Comment by natacha-beck** [comment]
Seems more like a bug to me and not a feature.As you said we have the CBCSV file to do that.

**Comment by natacha-beck** [comment]
Close by #1165

**Comment by prioux** [comment]
Closed by #1165
