### ISSUE TITLE
 Files with spaces in their name are ignored... 

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#115]
by the upload interface in the portal while an error message should be shown.

Redmine: Bug #7686

**Comment by eafkhami** [comment]
There was a redirect_to that prevented the flash message from showing. 

However there is a ajaxError method in Cbrain.js  that is called anytime there is a none zero request status. The error message from this method shows up first and then is overridden by the controller create method error message. This makes for a weird experience.
