### ISSUE TITLE
Broken link on `latest updates task` in NH

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#1176]
If a user has a task on his `personal project`. On the `Latest update tasks` on the `Dashboard` the link to the project will throw an error saying that the user have no access to the ressource.

**Comment by prioux** [comment]
A solution for this is to change our definition of a project in NeuroHub; initially only CBRAIN `WorkGroups` where presented. We should add the user's own `UserGroup`. It makes queries a bit difficult though.

**Comment by prioux** [comment]
The changes could probably be made entirely in the helper methods of `lib/neurohub_helpers.rb`
