### ISSUE TITLE
Don't show 'link to globus' when admin browsing a user's account page

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1179]
An admin can browse a user's account page, and if the user hasn't linked a globus account, the button 'Link To A Globus Identity' will show up. That button should be hidden. If the admin clicks on it it will make the link with the admin's account anyway.

Change in both CBRAIN and NeuroHub.

**Comment by prioux** [comment]
The template code should have something like

```erb
<% if @user.id == current_user.id %>
button code
<% end %>
```

**Comment by MontrealSergiy** [comment]
` @user.id == current_user.id` does not seem work

**Comment by MontrealSergiy** [comment]
@prioux should I check ` cbrain_session.user_id != current_user.id ` along with above?

**Comment by prioux** [comment]
Why doesn't it work? What happens?

No, do not access the session to make the check, that's not within the domain of the view code.

**Comment by MontrealSergiy** [comment]
and actually cbrain_session.user_id is also overwrited during switch.

**Comment by MontrealSergiy** [comment]
If there is no other mean to detect switched user we can add a new field to session and a helper to access it

**Comment by prioux** [comment]
Why are you talking about switching? This issue has nothing to do with switching user.

We just want to button to not show up when the current user is not the same user as the show page's user.

**Comment by MontrealSergiy** [comment]
Ok, maybe resolve now ignoring the switching case

**Comment by prioux** [comment]
Like I said this issue has nothing to do about switching.

**Comment by MontrealSergiy** [comment]
When admin switched account he also faces the similar situation - he can wrongfully attach his Globus identity to a regular user, though that's require a different check

**Comment by prioux** [comment]
Done in #1183
