### ISSUE TITLE
Overlays data provider exraneous single quotation mark in get_squashfs_basenames

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1182]
There is an unmatched single quotation mark in definition of the `get_squashfs_method`

```  remote_cmd  = "cd #{self.remote_dir.bash_escape} && ls -1'"```

(near the end of line 272 of sing_squashfs_data_provider.rb

The mark should be deleted it breaks new singularity overlays from functioning. It's mitigated by cache but will be issue if cache is expired or new models. The remote command fails, yet error is silenced, so cbrain just behaves as there are no overlays.

**Comment by prioux** [comment]
Fixed.
