### ISSUE TITLE
Store and validate checksum for task archives

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1186]
CBRAIN has the ability to tar up and task's work directory. The results is a TarWorkdirArchive file registered in the task's owner's file space. 

To prevent tampering with the archive, when the archive is created, a checksum of the tar archive should be computed and stored in the meta data of the task. When unarchiving is requested, the unarchiving code should validate that the tar archive has the same checksum as when it was created.

I suggest storing the checksum in the meta data of the task, and using the 'cksum' program to compute it.

**Comment by MontrealSergiy** [comment]
@prioux is it for accidental changes or really tampering? cksum command is not cryptographically secure: While it guards against accidental corruption (it is unlikely that the corrupted data will have the same checksum as the intended data), it is not difficult for an attacker to deliberately corrupt the file in a specific way that its checksum is unchanged. Unix-like systems typically include other commands for cryptographically secure checksums, An md5 or whatever cache could be more reliable

**Comment by prioux** [comment]
I know all that. It's to prevent tampering. Use md5sum if you prefer, I don't mind.

**Comment by prioux** [comment]
Note that md5sum doesn't exist on MacOS ; use something that works on both Linux and MacOS

**Comment by MontrealSergiy** [comment]
apparently Mac's have `mp5 ` command has a compatibility mode https://www.garron.me/en/bits/how-to-md5sum-mac-os-x.html. A sample wrapper https://stackoverflow.com/a/8996924. Or, to keep it simpler a Ruby lib can be used, at 100M/s it's probably a bit slow but archiving is async anyway

**Comment by prioux** [comment]
The command on mac is 'md5' and it has none of the options of md5sum on linux. The output is different too. Just invoke whichever is available and parse out the md5 checksum. keep it simple.

**Comment by prioux** [comment]
Mac:
```
Bianca master BrainPortal > cat README.md | md5
5c865179a88ad00f7bf63d19c2121f3c
```

**Comment by prioux** [comment]
Linux:
```
ace-cbrain-1 ~ > cat out.json | md5sum
20f1fb91d4a847a5d2ab51cec92a5d61  -
```

**Comment by prioux** [comment]
In fact just ` | tr -cd 0-9a-f` at the end and you're good to go

**Comment by prioux** [comment]
Done by #1204
