### ISSUE TITLE
Boutiques `value-disables` edge case.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#1191]
When using `value-disables` with some specific Boutiques descriptor we can fail in some edge case. 

See Boutiques descriptor as attachment (Github does not support .json attachment, that's why it is a .txt). 
[boutiques_demo_list_btq.txt](https://github.com/aces/cbrain/files/7722472/boutiques_demo_list_btq.txt)

Here is the sequence to produce the edge case: 

1. Select `autorecon2` in `stages` (--> will disable `List of numbers`)
2. Check option `-h` (--> will disable `stages`)

These 2 steps should re-activate the `List of numbers` options but it isn't the case.

**Comment by MontrealSergiy** [comment]
yes I reported something like that in the original feature ticket with an existing boutiques https://github.com/aces/cbrain/pull/1163#issuecomment-952355646

**Comment by MontrealSergiy** [comment]
@natacha-beck works now is it resolved?

**Comment by natacha-beck** [comment]
Tested on my dev server with the same descriptor mentioned in this issue, works fine on my side too. 

I will closed the issue.
