### ISSUE TITLE
New boutiques integrator, cbcsv and type checking

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1194]
The newly added to dev branch feature https://github.com/aces/cbrain/pull/1181 allows to specify restrictions to input file type using boutiques custom properties, e.g.

```
 "custom": {
        "cbrain:integrator_modules": {
           "BoutiquesFileTypeVerifier": {
             "sinput2": [  "MincFile", "FileCollection" ]
           }
       }

 }
```

however if cbcvs Cbrain File List file is passed as an input, instead of type of each file in the list, the type of said File List is checked. This is has no sense, since presently there is only one supported type of cbcvs files, and only confuses users. 

If checking type of each file in the list is too difficult, at the least disable this validation on cbcvs files as it was done for file name regex check.

To reproduce use a boutiques with a custom property as above, and supply cbcsv file that contains only Collections or MicnFiles .

**Comment by prioux** [comment]
This was already fixed in the last commit of PR #1181

**Comment by prioux** [comment]
https://github.com/aces/cbrain/pull/1181/commits/6b4c52ac1c309553d427c72d08bd66508789204d

**Comment by prioux** [comment]
Please verify and close this issue, it seems to not be relevant anymore.

**Comment by MontrealSergiy** [comment]
That commit only changes name matcher, not type matcher

**Comment by prioux** [comment]
OK, I'll make a patch for the type matcher too.

**Comment by prioux** [comment]
This is done in 0dcb50001
