### ISSUE TITLE
We cannot sort exceptions by date, revision, author etc in the exception log index

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#120]
The table head only sorts in one direction; clicking a second time is supposed to sort in the other direction (like for all other index tables). Some sorting headers cause new internal errors too.

**Comment by eafkhami** [comment]
According to Remi this will be fixed by the new dynamic index tables.

**Comment by prioux** [comment]
Good point. I'll leave the issue open until we have merged it. Re-assigning to Rémi in the meantime.

**Comment by remibernard** [comment]
Turns out that while this will be fixed for the new dynamic tables (as it'll most likely entail a refactor of the current session system to allow sorting and filtering everywhere), I was dead wrong about the source of the bug and it can be easily fixed without the huge changeset for dynamic tables.
