### ISSUE TITLE
Add support for 'other_group_id' in Swagger, for browsable DP registration API

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1207]
Our Swagger description doesn't include support for the attribute 'other_group_id' in the POST for registering files on a DP.

https://app.swaggerhub.com/apis/prioux/CBRAIN/5.1.3#/DataProviders/post_data_providers__id__register

I think it should go into the `multi_registration_mod_req` model (but I'm not sure).

**Comment by jesscall** [comment]
I agree with adding to `multi_registration_mod_req`

**Comment by prioux** [comment]
Fixed in dev by https://github.com/aces/cbrain/commit/30b5c69fcc40fafc99daa4dbf601d2e2422e501e
