### ISSUE TITLE
Users that are not member of a site generate exception when they go to /sites/12345

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#121]
The site 'show' page and controller always only show the single site that the user is member to. This is a problem if a user is not member of a site: the view code crash.

**Comment by prioux** [comment]
The actual ID is not even important in the URL

**Comment by eafkhami** [comment]
Cant reproduce the bug. I tried this with a user that isn't a member of a site and it doesn't crash.

**Comment by eafkhami** [comment]
This only happens if the user is not a member of any site and user.site is nil
