### ISSUE TITLE
Trying to edit a task belonging to another user cause an exception

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#122]
I think the controller code for ensuring proper user ID in the task object fails when a user edits the task of another user (which is in a shared group).

**Comment by natacha-beck** [comment]
I put labels, Milestone and assignee on this task, seems to be missing.

**Comment by eafkhami** [comment]
We (Pierre and I) can't reproduce the bug. Leaving it alone for now.

**Comment by prioux** [comment]
Will try to reproduce.

**Comment by prioux** [comment]
Postponed until it re-happens.
