### ISSUE TITLE
no "confirmation of account request" email being sent for registrations coming through NeuroHub

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#1226]
Hi,

A collaborator at Minnesota (Erik Lee) applied for an account twice last week (April 6 and 7) through the NeuroHub portal interface.  When looking at the signups page through the admin interface I noticed that the requests were both marked as "email unconfirmed".

I did some tests of new account requests, one through the NeuroHub portal and another through the CBRAIN portal.  Only in the case of the request created through the CBRAIN portal was an email sent to the applicant asking them to confirm their email and their account request.  No email appears to have been sent for the case of applications created through the NeuroHub interface.  

Can it please be checked if if the confirmation email is indeed part of the NeuroHub interface implementation, or if this is a bug?

Thanks.

Bryan.

**Comment by prioux** [comment]
Nothing's changed on that side. Could be be because of the DKIM record?

**Comment by prioux** [comment]
I suspect that because of DKIM, CBRAIN can no longer send emails as `support@neurohub.ca` ...

**Comment by bryancaron** [comment]
Does the confirmation email for account requests created through NeuroHub get sent such that they are to appear as coming from an email from the @neurohub.ca domain?  I don't recall.

It should not be related to DKIM since that only governs emails coming in from the Envoke email management system which identifies as coming from info@neurohub.ca.

**Comment by bryancaron** [comment]
I think our message writing in Github crossed.  :) So if such messages are sent as support@neurohub.ca then it may be related instead to the DMARC setting.

**Comment by MontrealSergiy** [comment]
@bryancaron I do not think DKIM is restricted to Envoke originated email, but general setup of email

which mostly consist in adding the DKIM key to our domain’s DNS records (neurohub's) and, typically, configuring postfix our whatever email server NeuroHub involves.

In the same time while exploring some preference page features of the Envoke service ('automated' emails) a representative changes some DKIM settings to increase 'automated' email deliver-ability. Should I follow up with them?

**Comment by MontrealSergiy** [comment]
also in my test www.mcgill.ca email address worked a bit better, with sending some emails messages into spam bin, rather than rejecting completely
