### ISSUE TITLE
Improve performance of table header filters

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#123]
Eshan and I tracked a particular interface performance problem to the SQL queries used to generate the filters in the table column headers. It's all related to the :format_source_id attribute, which cause real slowdowns with a large number of userfiles queries. The solution is to add a few more SQL indices:

```ruby
add_index :userfiles, [ :format_source_id, :type ]
add_index :userfiles, [ :format_source_id, :user_id ]
add_index :userfiles, [ :format_source_id, :data_provider_id ]
add_index :userfiles, [ :format_source_id, :group_id ]
```

This will work until we completely get rid of the format_source feature in CBRAIN anyway (see a future issue about this)

**Comment by eafkhami** [comment]
added this and did pull request
