### ISSUE TITLE
Get rid of the format_source feature

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#124]
This feature is barely used in CBRAIN; all references and dependencies to this feature should be surgically excised from the code base. The attribute is :format_source_id in Userfile.

Also check in all six of the cbrain plugin packages:

[MNI](http://github.com/aces/cbrain-plugins-mni)
[FSL](http://github.com/aces/cbrain-plugins-fsl)
[Freesurfer](http://github.com/aces/cbrain-plugins-freesurfer)
[PSOM](http://github.com/aces/cbrain-plugins-fmri-psom)
[Removed](http://github.com/aces/cbrain-plugins-removed) (private)
[Experimental](http://github.com/aces/cbrain-plugins-experimental) (private)

**Comment by eafkhami** [comment]
Removed this from code based and did pull request.

**Comment by prioux** [comment]
I did the surgery in the packages; Eshan did it in the main platform.
