### ISSUE TITLE
The 'prepare_tool_id' feature doesn't work in Firefox

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1240]
There's a problem with the JavaScript I think. It works in Chrome and Safari, but not Firefox.

I do get prompted to select files, but the file counter near the launch button never registers any selected files when I click the checkboxes.

Natacha, since you're the person who implemented the feature, can you debug this?

**Comment by natacha-beck** [comment]
I wasn't able to reproduced this issue (tested on my laptop and on my desktop) both with Firefox.

Did you test it with an `incognito` windows ? The files selection did not work properly in `incognito` mode.
