### ISSUE TITLE
[BUG] cannot select files if tool selected first

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1252]
Usually we select files first then tool, but scenario when tool selected first then input files
Regretfully, it is impossible to launch task the latter way, because Launch button stays grey-out after selecting files. Possibly duplicate

Steps to reproduce
1. go to userfiles
2. click launch
3. select tool
4. select file(s)
Expected Launch button right from the file selection activates
Observed actual behavior Right Launch button stays grey out 

![image](https://user-images.githubusercontent.com/11949081/181032283-ee269a9c-ffcd-4ddf-914b-506c8e1dfa02.png)
Chrome 76 sub-865762

might be related to #1240

**Comment by MontrealSergiy** [comment]
was not able to reproduce today ...

**Comment by natacha-beck** [comment]
Same on my side, I am not able to reproduce. I will close, we will re-open if it's happen again.
