### ISSUE TITLE
How to create a custom filter by file name prefix

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1256]
I created a custom filter, with name, file type, 

Filename: | Begins with, c

Child name contains (lists parents): | sub

Parent name contains (lists children): | sub

yet cbrains generates an error File name type both filename fields should be set if you want to filter by filename, is something missing or a bug

![image](https://user-images.githubusercontent.com/11949081/184234938-e607d8e0-74e2-4201-8940-d4bebcf6ae34.png)

**Comment by prioux** [comment]
The error message is horrible but I think it means you can't filter by both children and parents. You provided names in both search fields.

**Comment by MontrealSergiy** [comment]
Ok, now I see it's some obscure Opera issues, it renders one field less than needed, I figure some jquery isuue. Firefox and Chrome seems to do fine

**Comment by MontrealSergiy** [comment]
![image](https://user-images.githubusercontent.com/11949081/184656296-34dffc77-944f-4be0-9a46-c1fa85429bd1.png)

**Comment by MontrealSergiy** [comment]
chrome rendering

**Comment by MontrealSergiy** [comment]
now firefox seems fine

**Comment by natacha-beck** [comment]
Tested on Chrome I see no issue.
