### ISSUE TITLE
Task archiving inconsistency lead to jammed sync status

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#126]
Prereqs:

1- userfile is archived on filesystem (with tar properly in place)
2- userfile is by mistake NOT marked as archived
3- userfile is scheduled for archiving

Results:

Userfile's 'sync_to_cache' is invoked (or another ToCache action) but an exception
is raised (probably the archiving system detects the tar file) so the sync status stays to "ToCache"
forever.

VERY likely a consequence of issue #6 .

**Comment by remibernard** [comment]
Most certainly a consequence of issue #6: ([file_collection.rb:209](https://github.com/aces/cbrain/blob/155f84c0019e346a0e247435aecb0cf25ca00614/BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/file_collection.rb#L209))
```ruby
    Dir.chdir(cache_full_path) do
      SyncStatus.ready_to_modify_cache(self) do

        return "" if self.archived? # In case another process has already archived it while we waited.
        return "Archive file already exists, yet file not marked as archived?" if File.exist?(CBRAIN_ARCHIVE_CONTENT_BASENAME)
```

**Comment by prioux** [comment]
Will appear in a upcoming merge with Remi's code, so I'm closing right away.
