### ISSUE TITLE
Get rid of all methods/documentation that refers to version numbers using the subversion ID string

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#127]
Many text documents and method documentation refer to the old subversion way of fetching the version number of a file using the $RCS_VERSION string and parsing it. In fact the whole class CbrainFileRevision is built to internally maintain some sort of compatibility with this.

Get rid of it, and use only an abstract representation of git commit numbers and commit info (author, dates, etc).

Also get rid of config/initializers/revision.rb, which contain core class extensions, and rename/create the methods elsewhere (CbrainExtension module?)

Redmine: 6858

**Comment by crocodoyle** [comment]
working on this

**Comment by crocodoyle** [comment]
When replacing svn_id_rev, should I use the revision_info.commit or revision_info.short_commit?

**Comment by prioux** [comment]
The short ID should be good enough.

**Comment by prioux** [comment]
Fixed by #425.
