### ISSUE TITLE
Add a site-customizable policy page

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#128]
Within CBRAIN maybe it would be nice to allow the admin to write a "policy" page where users could be told about how the system is administered.

E.g. what data providers are there, how often the data is archived, if files get moved automatically why and when, how long are tasks kept or archived, etc.

This could be done by checking for the presence of a HTML or HTML.ERB file and presenting a 'policy' link to the user if found

**Comment by prioux** [comment]
Done with licenses.
