### ISSUE TITLE
Add userfile model for SquashFS files

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1293]
And in the view code:

```shell
unsquashfs -s file.sqs
unsquashfs -lls file.sqs
```
Note that if `unsquashfs` supports it, I recommand the second command (`-lls`) be run with also `-max-depth 2` so as not to list all the files in the squashfs file (the list might be big).

Addendum:

We could use this same view code for SIF files (singularity images, or apptainer images) by querying the offset of the squashfs filesystem:

```bash
singularity sif list sing_image.sif
```
```
------------------------------------------------------------------------------
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33101               |Def.FILE
2    |1       |NONE    |36864-154173440           |FS (Squashfs/*System/amd64)
```

then

```bash
unsquashfs -o 36864 -max-depth 2 sing_image.sif
```

**Comment by prioux** [comment]
Note that not all unsquashfs commands support all the options. I've seen 4.5 on compute canada and 4.2 on other system, and only the latest version support `-o` and `-max-depth`. The code should check it.

**Comment by MontrealSergiy** [comment]
are not views rendered on the portal (which does not support max depth)?

**Comment by MontrealSergiy** [comment]
a workaround for older unsquashfs could be add a grep or other filter for slashes

**Comment by prioux** [comment]
I implemented this a few minutes ago.
