### ISSUE TITLE
 Optimize filter creation code.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#130]
I'm not sure if it's possible, but I'd like to think of ways to make the code to build filters for index tables more efficient. One thing is I think I could do the query for the full list as a nested query in the second one. Another option is load attributes into memory as arrays (not full objects) using Pierre's raw_rows method, and then do one pass to build the filter lists.

I'm still not sure if either of these will be much faster then our current code, though.

Redmine: 3237

**Comment by remibernard** [comment]
Hmm, from what I've seen, SQL-wise, the best we can hope for is 2 single index traversals, as the application of custom filters nullify any advantages from fancy multi-column indexes. This is what we are currently doing.

I'm not exactly sure what is meant by nesting the queries; SQL-wise, there no nesting as both queries are essentially counts of different sets; one with filters on and one without. Nesting in Ruby (or loading all rows using raw_rows) wouldn't be advisable as that wouldn't make use of the database's indexes in the with-filters case.

I suggest keeping our current code as-is.

**Comment by natacha-beck** [comment]
No more relevant.
