### ISSUE TITLE
Userfile show issue when file is not locally sync.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#1301]
When looking at a file viewable by BrainBrowser that is not locally sync I get the following issue: 

![image](https://user-images.githubusercontent.com/777590/216714899-39ae73c9-d546-463f-b8ae-8cb1e2e4342e.png)

My suggestion is to look if the file is locally sync at l278 of `app/views/userfiles/show.html.erb`, here: 
https://github.com/aces/cbrain/blob/master/BrainPortal/app/views/userfiles/show.html.erb#L279

**Comment by prioux** [comment]
Fixed in latest commit  https://github.com/aces/cbrain/commit/001bb92a98fb50d0ddab99280f82e8fe2b02f411

**Comment by prioux** [comment]
The ONLY place where we have a viewer with direct data provider streaming is in the MacaccCollection (yes, spelled correctly), which is no longer supported anyway. So we're good I think.
