### ISSUE TITLE
 Don't like the Userfile#update_file_type method.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#131]
It's clunky, couples the Userfile and User models, and doesn't use the new type validations, meaning we have type-checking logic in two different places. It's only used in one place, UserfilesController#update_multiple, so I think we should be able to get rid of it (and possibly other methods that only it depends on).

Redmine: 3211

**Comment by prioux** [comment]
Cannot find code that was bad... Remi to investigate.
