### ISSUE TITLE
BTQ integration: error save result with *.mat folder. 

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#1315]
I have a tool ([mcflirt](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/MCFLIRT))  that produce a folder named *_mcf.mat. 
When running the tool I get: 

> CbrainError: Error: incompatible directory 'D99_template_pd_mcf.mat' given for a SingleFile.

My first try to fix the bug was to set `BoutiquesOutputFileTypeSetter` for the output to `FileCollection` but it still failed because it is ignore in `name_and_type_for_output_file` of `boutiques_cluster_task.rb`.

**Comment by prioux** [comment]
Can you please provide a proper explanation? When does this happen? During post processing? What is in the descriptor in the output section? What are the files present in the work directories? COuld it be you have BOTH a file and a directory that ends with `_mcf.mat` ?

**Comment by natacha-beck** [comment]
@prioux the issue is that [l334](https://github.com/aces/cbrain/blob/master/BrainPortal/app/models/boutiques_cluster_task.rb#L334)

return a FslMatrixFile and a FslMatrixFile is a SingleFile.

**Comment by prioux** [comment]
OK so I'll add a piece of code that compares the suggested type to the actual filesystem content we're trying to save, and reset to 'SingleFile' or 'FileCollection' if there is a mismatc. This should go just after line 250.

**Comment by natacha-beck** [comment]
Closed by commit: https://github.com/aces/cbrain/commit/431055c4a7fe97ecfdd9dfc1aed6c26bad44aa8f
