### ISSUE TITLE
SyncStatus docs

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1330]
SyncStatus' status_transition method docs say

This method changes the status attribute in the current _task_ object

should be sync_status status instead? Is so, correct to reduce confusion?

also, docs says lock ensures collision of two status updates, which is not 100% accurate.
MySql is arguably 'lightweight' db

mysql Innodb lock reduces chances of issues, but does 100% guaranty absence of [phantom writes ](https://blog.pythian.com/understanding-mysql-isolation-levels-repeatable-read)
(duplicating sync objects), so as you done recently db uniqueness constraints are typically used

**Comment by prioux** [comment]
Documentation adjusted, will go into a future commit.
