### ISSUE TITLE
Cabinet on CBrain Help

### ISSUE THREAD

**Issue by cgregg1227** [aces/cbrain#1342]
Our lab is attempting to use Cabinet on CBrain but we continue to not get output when running it. Based on what I was looking at in our log it looks like it should be generating an output, but we haven't gotten any output from our attempts. If possible, would you be able to take a look at our log and see if you can identify the problem? See log below:

[cbrain - Cabinet log.pdf](https://github.com/aces/cbrain/files/12174859/cbrain.-.Cabinet.log.pdf)

Thank you for your time,
Collin

**Comment by MontrealSergiy** [comment]
Hi Collin, the best place to discuss specific tool issues on CBRAIN portal is our user support forum at https://forum.cbrain.mcgill.ca or use the support email. Please indicate the url of the failing task. In github we mostly tract cbrain codebase bugs and issues

**Comment by MontrealSergiy** [comment]
Also please do not saver results directly to  sftp-1 dataprovider, it lacks capacity and bids-required features. Save your results on Beluga-local or [MainStore](https://portal.cbrain.mcgill.ca/data_providers/27) , then move them to sftp if you need to download them with a ftp client. @prioux do you think we should limit use of sftp-1 for such pipelines programmatically?

**Comment by prioux** [comment]
Tomorrow I will close this issue and reopen it in our ticketing system. Please do not continue the discussion here in the meantime. I already looked at the problem and there are several issues to address.

**Comment by prioux** [comment]
Will transfer the question ti the issue tracker.
