### ISSUE TITLE
Some read-only DPs return false for "read_only?"

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1399]
Some DPs are meant to be read-only. Usually, they inform the rest of the system by just overriding the method read_only() in this way:

```ruby
def read_only
   true
end
```

The attribute read_only is a database column. However, for boolean columns, Rails also provide `read_only?` . Since that method is not overridden, it returns false if the DB's value has not been set. So we get this kind of behavior:

```ruby
irb> d.read_only
 => true 
irb> d.read_only?
 => false 
```

There are several solutions. Not sure what is best.

1) make sure the DB column is also consistent; maybe with a general callback in after_update()  ?
2) override `read_only?` too
3) ...
4) profit!
5) my slashdot ID is 5 digits long

**Comment by MontrealSergiy** [comment]
I guess I'd add an alias to DataProvider.read_only. And database value for greater consistency.

**Comment by MontrealSergiy** [comment]
Well, I would go for variant 2 because it is probably enough to overwrite method in the parent class and it affects the method immediately on creation. Also, optionally, variant 1 can be implement in the same time, just to make db more consistent, is not big deal either

**Comment by MontrealSergiy** [comment]
Actually not only boolean, any attribute has 'truthiness/presentishness' check method, which differs only in question mark, something like `name?`, `type?`, 'description?' etc ... Note integer 0 considered by falthy falue.

**Comment by MontrealSergiy** [comment]
@prioux Should I work on it, or would you prefer to take care of it yourselves?

**Comment by prioux** [comment]
Fixed all the DPs with an explicit

```ruby
def read_only?
   true
end
```

**Comment by prioux** [comment]
https://github.com/aces/cbrain/commit/fab9c9193e176e42f4d8f7f7d41088d3f2cf7a00
and
https://github.com/aces/cbrain-plugins-neuro/commit/f8f656d27f486ffe67a031fc040b0998a6908663
