### ISSUE TITLE
no buttons on Mandatory OIDC link page (unless OIDC is configured)

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1418]
To reproduce you would need to have a OIDC free user account, and make sure there is no changes into OIDC yaml config file, or OIDC variable. 

After login as such a user a Mandatory OperID provider Link page will be rendered

The page text will say click on the button yet there is no button on that page.

This is confusing I would say there should be some contact admin message.

Well, cbrain page has contact CBRAIN adminstrator for more information in the very end, but not Neurohubs. Or better run a validation of OIDC presence on start.

Ideally I would make this OIDC optional for dev mode.

**Comment by prioux** [comment]
This is not a bug. If there are no OIDC provider configured, users should never see the mandatory link page anyway.

**Comment by prioux** [comment]
I don't see anything private in the `oidc.yml.erb` file...

**Comment by prioux** [comment]
Okay I can see we could also name it with a `.template` extension so that it forces a sysadmin to copy the file.

**Comment by prioux** [comment]
I think renaming the file with ".template" and forcing the admin to copy and edit it is a good idea. That way, a "git status" won't report a changed file for no reason.

**Comment by natacha-beck** [comment]
It is already under `.template` no: 

- [https://github.com/aces/cbrain/tree/master/BrainPortal/config](https://github.com/aces/cbrain/tree/master/BrainPortal/config)

**Comment by prioux** [comment]
You are right.

So it the initial issue still valid @MontrealSergiy  ? If not please close this issue.

**Comment by MontrealSergiy** [comment]
right, looks like you renamed the file soon after issue reporting. I guess I did not notice. I am closing the issue
