### ISSUE TITLE
Contact us hyperlink on cbrain portal

### ISSUE THREAD

**Issue by xmpham** [aces/cbrain#1421]
On the portal cbrain, once logged in, there is no **contact us** link available. Should/Could we add it somewhere, maybe on the dashboard? the contact us is currently available only on the main page, cbrain.ca

**Comment by MontrealSergiy** [comment]
it is called support email in cbrain and should be set in console. 
 ```RemoteResource.current_resource.support_email="cbrain-support.mni@mcgill.ca" ```

In other words it is support/administration task not development
