### ISSUE TITLE
file search for a number terminating with underscore results in an exception

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1434]
To reproduce in file search field enter `24_` or enter url
	https://portal.cbrain.mcgill.ca/userfiles?name_like=24_&_=1727287061912

One would expect CBRAIN quietly return list of files starting with 24_ , and yet an exception is generated during yaml serialization of the string. 

Perhaps, as a workaround one may add quotations over the string.
In a rails  5.0.7 console/ ruby 2.7 `'2_'.to_yaml` generates an exception, but rails works fine with  for  `'"2_"'`.to_yaml 

The issue is corrected in more recent psych releases, see PR `https://github.com/ruby/psych/issues/442`
Updating to recent psych would be more clean bug fix but will require all developers to update their setup

**Comment by MontrealSergiy** [comment]
I tried to update to the latest psych (5.1.2) but got `Tried to load unspecified class: Time` error at during CBRAIN 'initial check'

**Comment by prioux** [comment]
I already fixed this. See https://github.com/aces/cbrain/commit/435a1334708cadbe7b080d4767c434aaffd2c79b

**Comment by MontrealSergiy** [comment]
That's a great workaround, but upgrading would save us from the same issue around the whole application. While the latest releases of psych 4 and 5 are too advanced, 3rd version seems to do the trick ` gem "psych", '~> 3.3' `
