### ISSUE TITLE
Fetching lists of objects by pages with the API does not stop sometimes

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1446]
The controller code we have in general has safety adjustments performed on the pagination parameters "page" and "per_page". If the page number is greater than the number of pages in the collection, it is set to the last page number before rendering. This works fine for browsers, and it means the user can adjust the page number to 1,000,000 and just get to the last page anyway.

But for API calls, where there client is asking page after page after page in a series of calls (by increasing the page number), if it happens that the number of entries in the collection is an exact multiple of the page size, the client will get the last page, increase it by one, and then get the content of the last page again. The client won't be able to detect that it has reached the end. Note that if the total number of entries is not a multiple of the page size, the client can figure out it has reached the end because the number of entries will be less than then page size, so that's okay.

We need to adjust the code such that we return an empty list for API calls with a page number greater than the total number of pages.

**Comment by MontrealSergiy** [comment]
In past I would usually just add some flag that indicate the last page, or link to next page, or just a number of pages depending on needs or preferences of client. But empty list might work too.

**Comment by prioux** [comment]
Fixed in https://github.com/aces/cbrain/commit/ebe490311800c27643f92578c3082f462925de7b
