### ISSUE TITLE
Processing of read-only files

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#156]
Read-only files cannot be processed by any task.

Error message: "You must select at least one file to which you have write access."

**Comment by Najmahan** [comment]
I JUST had the same problem dealing with another group project. This is not a very logical restriction, so must be a bug?

**Comment by prioux** [comment]
What would help is if tasks would provide a hint as to whether they modify their input files or not. Assume "not".

So maybe a new task property. If the property exist we can trust it.

Right now, the only CbrainTask what modifies its input is CbrainTask::CivetQC (in package cbrain-plugins-neuro) which modifies a CivetStudy userfile.
