### ISSUE TITLE
Code to extract files from browsable data providers to be made more robust for illegal UIDs and GIDs

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#159]
The code that generate the list of files, when browsing a data provider, tries to create a FileInfo obejct with standard UNIX attributes such as UID and GID, and mapping them to their names using getpwuid() and getgrgid(). When the UIDs or GIDs are not legal, an exception is raised. Maybe investigate how to make that more robust (maybe create dummy names with the numeric ID as a string?)

Note: there are several places where such  browsing code exist, for there are variations based on each distinct subclass of DataProvider.

**Comment by remibernard** [comment]
There seems to be only one problematic set of calls to `Etc.getpwuid` and `Etc.getgrgid`, and both are in `LocalDataProvider`; [`local_data_provider.rb`:91](https://github.com/aces/cbrain/blob/master/BrainPortal/app/models/local_data_provider.rb#L91), [`local_data_provider`:95](https://github.com/aces/cbrain/blob/master/BrainPortal/app/models/local_data_provider.rb#L95)

A quick `grep` did not find any other browsing code using those, and I would assume `Net::SFTP` to handle those issues for `SshDataProvider`. Where else could this issue occur?
