### ISSUE TITLE
Boutiques integration

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#160]
1. Basic integration: multiply tasks only when tool has a single input file. When tool has more than 1 input file, then only 1 task is created. 
2. File and parameter lists for multiple inputs are specified in a CSV file. Drop-down menu allows to change the input associated to the list. A checkbox allows to specify that the first line in the CSV file is the input name.
3. File list selection in task interface (with filters, sort, etc). With only 1 input list. 
4. Support for multiple file input lists. Lists are combined one-by-one (when both lists have multiple elements), or all-to-one (when one list has only 1 element). Lists with multiple elements all have to have the same number of elements. 
5. Parameter multiplication with "all-to-all" (a.k.a cross) operator by default.

**Comment by remibernard** [comment]
Additional notes to support multiple tool versions:
- A new wrapper class is used (with the same name) instead of the main `CbrainTask` tool subclass, which contains the Ruby `Class` instances generated for each version of the tool (in a class variable, for example).
- This wrapper class' instances wait until a `ToolConfig` is associated with it, then delegates all operations to the subclass matching the config's version.
- `remove_const` can be used to remove a class from its parent and returns the `Class` instance.

**Comment by glatard** [comment]
Following recent discussions and experience, it is still not clear how we want to handle tools that have more than a single input file (item 2. to 5. above). The basic options are:
A. Add all the files selected by the user to all the input lists, and let the user choose more than 1 file in these lists. This is easy to do but it doesn't scale well to more than a few files (users won't click on 100 files). 
B. Let the user provide a CSV file where the first line of this CSV file contains input ids, and each row corresponds to a particular task to generate. This is powerful but it's a shortcut in the CBRAIN framework.
C. We don't support tools with more than a single input file (or directory). Tools that take more than a single input have to be modified to, e.g., find the relevant files in a single directory. 

This requires discussion...

**Comment by ttaa9** [comment]
Given that I was just asked how to run a boutiques tool on 600 datasets, I think B seems to be the best. C might be complicated; e.g. for ica-aroma there are multiple input files, some with the same extension and some that could feasibly have multiple allowable types, that could conceivably be called anything. Also, it might be a huge annoyance for people who just want to run the tool once. And, like you said, A may not scale too well.

I am not sure how the CSV should be formatted though, especially if one wanted to run the same task with multiple, differently named inputs many times, in such a way that the format could be used across all boutiques tools. Maybe they should provide a json descriptor with the names of the inputs or something, with one entry per task.

**Comment by prioux** [comment]
Structured inputs?
An input for a tool that has two or three files of different types might be required to be a models as a directory with the two or three files, and that directory is given the type 'SomethingInput". Then when launching 600 such tasks, the user simply selects 600 'SomethingInput' entries (each with 2, 3... n files properly structured)

**Comment by glatard** [comment]
@prioux that basically requires that tool developers modify their tools to use a directory rather than multiple files, or that someone writes and maintains a wrapper script for the tools. These wrappers are likely to be CBRAIN-specific and will thus have to be maintained by us. It defeats a bit the purpose of the Boutiques integration system.

A solution would be to specify a generic model that would apply to any Boutiques tool. The directory structure could look like this:
```
input_id_1/file_name1.ext
input_id_2/file_name2.ext
input_id_3/file_name3.ext
```
The Boutiques wrapper would then map file_name1.ext to input_id_1, file_name2.ext to input_id_2, etc. The user could input several of such collections. @prioux, do you think it would make sense?

The problem I see with such "models" is that files have to be renamed and re-organized every time a new experiment has to be started. A CSV-like approach addresses that.

@ttaa9 the CSV file would definitely be tool-specific.

Also, I still believe that solution A. above would be useful when a few files (<10) have to be processed.

**Comment by glatard** [comment]
After a few more thoughts and discussions with @natacha-beck and @ttaa9, I think the best option, although not ideal, is the CSV one. The model option suggested by @prioux and described in the previous post is limited. In particular, it will not scale in these cases:
- a file is used in multiple tasks: it should be duplicated in all the file collections.
- a set of file has to be processed by different tasks: they should be copied in different file collections.
This will require a lot of file collection creation and editing, which is not easy to do at scale from a GUI. I understand @prioux's concern that the CSV thing circumvents the CBRAIN model but I don't see any other possible solution yet. 

@tta9, @prioux, @merous and @natacha-beck, what do you think?

**Comment by ttaa9** [comment]
A csv seems easier to create for the user. Also, for example, if one wanted to launch tasks for different values of a number parameter (say for parameter optimization), a csv also seems easier.

**Comment by glatard** [comment]
Following our discussion today, here is the current solution:
1. A new model is introduced to represent "CBRAIN file lists".
   * CBRAIN file lists are implemented as a new file model that inherits from CSV file.
   * Users can create CBRAIN file lists from an ordered file index (new option in the burger and contextual menus of the file index page), or import file lists from CSV files.
   * A CBRAIN file list is a CSV file where the first column represents a file id, and the subsequent columns are file attributes (e.g.: name, data provider, owner, project). Attributes are used only for readability purposes but not by the CBRAIN framework.
   * File id 0 in a file list represents an empty element.
   * A  CBRAIN file list has methods to validate the list, i.e.: check that the file ids exist, that they are accessible by user X, etc.

2. Support in Boutiques:
   * The launch form of a Boutiques tool basically doesn't change. When the tool has multiple inputs with type File, the user is still able to select only 1 file per input of type File. This file, however, can be of type CBRAIN file list.
   * The `generate_final_task_list` method of a Boutiques tool is modified to account for CBRAIN file lists. Let's consider a tool with 2 inputs of type File: input A and B. When input A contains a file list and input B contains a regular file, then a task is created for every element in input A. All these tasks will process the file in input B. When input A and B both contain a file list, then they have to have the same number of elements (empty element can be used if necessary). A task is then generated for every (input_A[i],input_B[i]) pair. The same principle is extended for more than 2 inputs.
  * A "task preview" option could be added to show the final task list that will be generated from the current input before the user clicks on the launch button.

**Comment by ttaa9** [comment]
This seems quite sensible. Also, note that I think a blank (i.e. ,,,...) is also considered an empty element right now.

But, how does this work with Boutiques inputs of type 'File list'? Presumably, we could put a cbrain_csv into any input of type File (i.e. with list : false) in a boutiques task and it would launch a task for each one. Or can a cbrain_csv only be used for File inputs with list : true? 

I am also asking because some tools like fsl_fast _can_ actually take in multiple (independent) arguments, each of type file list (literally meaning multiple files on the command line here) for a _single_ task, which we cannot support right now in cbrain.

**Comment by glatard** [comment]
If `list` is true then the elements in the `cbcsv` file will be added to a single command line, while if `list` is false then a task will be created for each element in the `cbcsv` file.

**Comment by ttaa9** [comment]
I think that is a good idea. It is not obvious when a a parameter has `list` being false vs true (on the task launch page) though, so we should put some kind of marker for this behaviour (although the preview table will show it as well). 

Although, one day, someone may want to launch multiple tasks over a parameter with `list` being true.

**Comment by glatard** [comment]
We could add a small icon when the parameter is a list, e.g "[ ]". 

When someone wants to launch multiple tasks over a param with list being true, we will have to support lists of lists. I guess it's already possible to define a list of list in a cbcsv file (i.e. a cbcsv file where elements are cbcsv files). It's "just" something to support in the task generation method.
