### ISSUE TITLE
Testing suite cb_error() undefined.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#178]
According to description in issue #76: 

The failed tests are due to rspec's File mocks interfering with Rails' autoloader; some tests require mocking File.directory? to always return true, which causes the autoloader to incorrectly consider unknown class (and module) names as modules under the currently active module.

See dependencies:431 and dependencies:505
I have no idea how to cleanly fix this. It could potentially

**Comment by prioux** [comment]
@natacha-beck Wasn't this fixed already in my commit https://github.com/aces/cbrain/commit/eac781ec60908a538e0ce94f46f8cf5af9b81c4e ?

**Comment by prioux** [comment]
Fixed by #415
