### ISSUE TITLE
Notify users when they are invited to join a common project (Redmine 7822)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#181]
(From Najmeh:)

Is it possible for CBRAIN to send an email to CBRAIN users who are invited to join a common project?

**Comment by prioux** [comment]
Not too difficult to do. The 'inviter' user should be provided an option to notify by email the invitees, though.

**Comment by crocodoyle** [comment]
Invitations appear to now always send emails, so this can probably be closed

**Comment by prioux** [comment]
Yep.
