### ISSUE TITLE
Task index: expanding a batch does not apply filters (Redmine 2763)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#191]
Clicking on 'expand batch' reveals the full list of tasks int he batch instead of applying the current filters. Which is weird, because the batch header BEFORE clicking showed the proper task stats.

**Comment by prioux** [comment]
Remi tells me this is fixed.

**Comment by remibernard** [comment]
Substantiating my statement, the 'expand batch' button fetches the list from the [`batch_list`](https://github.com/aces/cbrain/blob/master/BrainPortal/app/controllers/tasks_controller.rb#L118) action of `TasksController`, which builds it from the list of tasks in the batch (`current_user.available_tasks.real_tasks.where(:batch_id => params[:batch_id])`) filtered by [`filter_variable_setup`](https://github.com/aces/cbrain/blob/master/BrainPortal/app/controllers/tasks_controller.rb#L992) which applies the current filters.
