### ISSUE TITLE
Error message in userfile archiving report is incomplete

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#20]
When archiving some files, I got an error with one of them.
The error message is missing the exception's message. See
picture below.

![err](https://cloud.githubusercontent.com/assets/777588/7091236/5ac59e32-df76-11e4-80c3-7ea675f2d36e.png)

**Comment by remibernard** [comment]
Is there a way to reproduce this?

This is a strange issue as there does not seems to be a single call to `cb_error` without an associated message in the codebase (the only reference to `CbrainError.new` is in `cb_error`) and the corresponding `rescue` block *does* incorporate the message ([file_collection.rb:243](https://github.com/aces/cbrain/blob/master/BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/file_collection.rb#L243)):
```ruby
  rescue => ex
    File.unlink(temp_tar_file) rescue true
    return "Archiving process exception: #{ex.class} #{ex.message}"
```
