### ISSUE TITLE
Broken tag filtering

### ISSUE THREAD

**Issue by remibernard** [aces/cbrain#201]
![tag_bug](https://cloud.githubusercontent.com/assets/12155323/9581352/00534b44-4fcd-11e5-85aa-789d56c1a15a.png)
Seems caused by the special format of tag filters:
`{ :parameter => :filter_tags_array, :value => 1, :class => "" }`
which is not recognized by dynamic table's compatibility layer, which only supports
`{ :filters => { "data_provider_id" => 22 } }`

**Comment by prioux** [comment]
To fix soon. Thanks for noticing.
