### ISSUE TITLE
Bourreau and Portal choke when DB contains tasks of tools in uninstalled plugins.

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#206]

**Comment by remibernard** [comment]
A somewhat clunky solution to this issue is what is outlined in issue 7044 (redmine) (commit 7c8cc3690c6370ff6698a61c8530c6307f3cac61). The rake task `cbrain:plugins:clean:orphans` will remove these bogus tasks.

Maybe a check could be done when the Bourreau/Portal starts?

**Comment by glatard** [comment]
What about catching the exception(s) and handling them without clearing the tasks?

**Comment by remibernard** [comment]
That would be at every single point where a task query is performed, for a condition which is (supposedly) rare and exceptional.

Assuming the plugin task classes use STI, one possible solution would be to rework the STI system a bit to have a fallback (`UnknownTask`?) class or just ignore those records.

If the plugin system just uses AR directly, then, short of heavily monkey-patching AR, I dont see a clean way out of this.

**Comment by prioux** [comment]
Do not fix or patch. It's normal and ok for things to go wrong: it means the admins has badly set up the system. The fix is simple: clean the DB.
