### ISSUE TITLE
 Refactor the surface_viewer.

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#21]
(Original Redmine issue by Natacha)

In the surface_viewer, we have:

``` ruby
# Extract obj file
surface_dir         = @userfile.try(:surface_dir) || "surfaces" 
surfaces_obj        = @userfile.list_files(surface_dir).map(&:name).select { |n| n =~ /\.obj$/ }
rsl_surfaces_obj    = surfaces_obj.select { |name| name =~ /_rsl_/ }
no_rsl_surfaces_obj = surfaces_obj - rsl_surfaces_obj
surfaces_obj        = no_rsl_surfaces_obj.sort + rsl_surfaces_obj.sort
surfaces_obj        = surfaces_obj.map { |file| Pathname.new(file).basename }
#...
#3. Combine
overlay              = thickness_txt_for_select + surfaces_txt_for_select
```

The logic in order to have the overlay and the surface should be outside.

**Comment by crocodoyle** [comment]
I would like to work on this but I don't know how to install CIVET so I can test it

**Comment by prioux** [comment]
You don't need CIVET, just a CivetOutput file.

**Comment by prioux** [comment]
Ah, nah I was wrong, it's true you also need some minc tools too... I forgot.

**Comment by crocodoyle** [comment]
This is addressed by PR 75 on the cbrain-plugins-neuro project

**Comment by prioux** [comment]
Yes, this issue really should be in the other repo. Link for quick reference:

https://github.com/aces/cbrain-plugins-neuro/pull/75

**Comment by natacha-beck** [comment]
This was fix in cbrain-plugins-neuro. So I will close this here. We still can re-open it if needed.
