### ISSUE TITLE
Support for public datasets (Redmine 2895)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#214]
(Feb 2012)

CBRAIN will soon be hosting public datasets (ICBM, ADNI, Big Brain).
- A special index page showing all public datasets should be created.
- These datasets should not "pollute" the user files unless the user wants it.
- Some new users should be able to register in CBRAIN only to access these datasets (no compute per default).
- These datasets should be available through SFTP and HTTP downloads.
- Users should be able to read all files of public datasets, but not add files to them.
- These data should not be duplicated to all users.
- Common results should be pre-computed and available to all user (like basic CIVET on ICBM).
- Users could upload contributions which would be evaluated for inclusion in the public sets...?

**Comment by natacha-beck** [comment]
I think we can close this one, we now have this part in NH. @prioux, @bryancaron, @MontrealSergiy ?

**Comment by prioux** [comment]
This was pretty much implemented in NeuroHub with the new 'public' attribute for WorkGroups.
