### ISSUE TITLE
Group selections needs to be less awful (Redmine 3017)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#217]
(From Tarek, March 2012)

At least for admins. It's just one giant, ugly select box, and you usually need to scroll down to the bottom to get what you want.

**Comment by prioux** [comment]
Ajax dynamic selection box.

**Comment by crocodoyle** [comment]
Fixed in Bootstrapification

**Comment by prioux** [comment]
Duplicate of #663

**Comment by prioux** [comment]
Fixed by #906
