### ISSUE TITLE
Selecting CBRAIN output files (Redmine 7925)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#229]
(From Najma, summer 2015)

This is related to the objective of making MINC and other softwares interoperable.

Scenario: CIVET performs superior to FSL tools in brain extraction function. I like to combine FSL's functional suite but take advantage of CIVET outputs at the same time. For example, FSL fails on brain-masking miserably and I would like to use one set of files in the CIVET output "mask" directory to fix that problem.

Desired solution: I like to have an option in CBRAIN that allows me to use files that are in the CBRAIN output directory structure as inputs to other tasks.
Or simpler, I like to take advantage of a CBRAIN filter that allows me to create a "collection" from a particular file in a CIVET sub_directory.

Any thoughts on this?

**Comment by prioux** [comment]
We have several experimental code frameworks that approach such problems, but none of them are ready (or are just at the planning stage). Yes, it would be a useful feature.

1- generic data reformatter: select a bunch of files or file collections, enter a rewrite rule, and create new files repackaged differently, suitable (Issue #40)

2- register files that are part of other files (Issue #168)

3- proxy objects (experimental code by Rémi, still in private branch, too unstable)

**Comment by natacha-beck** [comment]
Similar to what Carolina want: 

> 
> CIVET customization
> a. Running mincbet to alter parameters of the brain mask required for brain extraction.
> Below is the mincbet command to implement to create a new brain mask, with recommended values:
> 
> mincbet <final/Prefix_ID_t1_final.mnc> mask -n -m -h 1.15 -f 0.50
>  
> The above command should be applied to the final t1 image (in the "final" CIVET output directory).
> The values for flags "-h" and "-f" can be altered by the user, to something like -h 1.10, and/or -f 0.6.
> We will have to keep in mind a way to keep the "old" mask in /mask/Prefix_ID_brain_mask.mnc, before replacing it with this newly created mask.

**Comment by crocodoyle** [comment]
Is this issue still relevant? There is now a way to extract files from FileCollections, and a recent PR of mine will make it easier to download files from inside a FileCollection
