### ISSUE TITLE
Notes on upgrading to Rails 4 (Redmine 6832)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#231]
Rails 4 is sufficiently different from Rail 3 that we will need to refactor some significant pieces of code.

This issue is created in order to list what is currently known about this. Separate issues will be created to track each subtask, as needed, when the work starts.
- attr_accessible() doesn't exist anymore; we must use the "strong_parameters" gem instead and add a private method in the controller to whitelist params as needed.
- As a side effect, Tarek's mass_assignment_authorization.rb module must be discontinued
- DB relations that use the "OR" keyword in a string can be replaced by the new proper ActiveRecord::Relations operators

**Comment by natacha-beck** [comment]
Definitively can be closed after several months of work we have [CBRAIN running on Rails5](https://github.com/aces/cbrain/releases/tag/5.0.0)
