### ISSUE TITLE
Persistently selected files must be deselected once operations are triggered

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#262]
I've been bitten by this too many times: when there are files persistently selected and I trigger an operation (archive, move etc) the files are still selected after the operation; then when I start planning another operation I forget that the files are selected and the new operation gets applied to the wrong set of files. We should add a bit of code that deselects all file when a button such as "archive", "move", "copy" etc is clicked.

**Comment by remibernard** [comment]
This is trickier than it may seem at first glance; clearing the persistent selection set after an operation isn't the persistent selection module's job. That task belongs to the button that launched that operation, which is implemented in userfiles' server-side templates using the higher-level `hijacker_submit_button` view helper (in which it would obviously be inappropriate to clear the selection).

**Comment by prioux** [comment]
Everything can be solved with callbacks.
