### ISSUE TITLE
Gather a list of version numbers of gems in Portal and Bourreau and add them to Gemfile

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#266]
Many of our gem listed in our two Gemfile 's don't require a specific version; this cause problems when they are upgraded and they no longer work.

Find the version numbers that are installed and known to work with the current version of CBRAIN, and add specifications to restrict them to these versions. If possible:

1- look at production servers
2- look at dev stations too

See also issue #265 for the discussion that triggered this issue.

**Comment by natacha-beck** [comment]
@prioux I think this approch: 

https://robots.thoughtbot.com/a-healthy-bundle

I think it's not a good idea to be too strict for some gem. I already have the list of gem version both on production and locally. So I want to know how much should I be strict.
