### ISSUE TITLE
Select all files feature crashes with large number of files.

### ISSUE THREAD

**Issue by merous** [aces/cbrain#274]
Attempted "Select all files on all pages" with 6298 files, the system returned with an un-handled error "We're sorry, but something went wrong".

**Comment by remibernard** [comment]
Does this bug occur using the new persistent selection mechanism present in dev? Or with the old one still in production?

**Comment by prioux** [comment]
With the old one in production. Maybe it would work OK with the new one in dev, though.

**Comment by remibernard** [comment]
I doubt the new one in dev has the same issue; I just tested it with over 160000 files selected and it works just fine (albeit a bit slowly).

**Comment by prioux** [comment]
OK, we'll try it once we merge dev. Thanks for the info. I'll leave the issue open for the moment.

**Comment by prioux** [comment]
Fixed in dev.
