### ISSUE TITLE
Browser cache clearing necessary to recover from some 500 error 

### ISSUE THREAD

**Issue by merous** [aces/cbrain#275]
When session enters a bad state the browser get the "We're sorry but something went wrong" message.
It is sometimes impossible, as in bug #274, to relanch a valid session without clearing the browser cache.

This can cause a problem if a user is unaware of the necessity to clear the cache, causing him/her to get the impression that the platform is down.

**Comment by prioux** [comment]
Was happening in older code, in new code this will not happened (verified with Rémi).
