### ISSUE TITLE
Minor issues in new launch tool interface

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#291]
- [ ] Tool search could be improved. For instance, typing "melodic" doesn't return "fslmelodic" (because "fslmelodic" doesn't start with "melodic"?)

**Comment by remibernard** [comment]
Also:
* It would be nice to be able to select a tool by clicking anywhere in the tool element, not just the tool's name.
* The dialog's contents sometimes shows up at the bottom of the UI while the page is loading.
* Resizing the dialog is apparently possible, and results in extra whitespace.
* Nitpick; once a tool is selected, there is an odd amount of extra whitespace added at the end of the tool element.

**Comment by glatard** [comment]
* Tags ("cluster", "diagnostics" and "life cycle "</html>") look wrong.
* Unclear what "Type ("internal")" and "Software package ("CBRAIN")" are.

**Comment by prioux** [comment]
More bugs:

1- had two filters active: one a table cou,n flter, and one a custom filter. They were DataProvider=MainStore, CustomFilter=(file is a file collection, not archived, not modified in 4 months)

2- only two files matched those filters, as expected

3- selected both files with global check box and clicked "compressed"

4- submit was successful, but after page refresh, only the custom filter was applied (so was seeing thousands of rows for files on other DPs)

I think it might be related to the fact that the current "state" of the filters is not entirely stored in the DB, but some info is stored in the rails instances, and we have 4 instances in the dev server. the one showing the view before the compress POST and the one showing the view after were not aware of the same filters.

**Comment by remibernard** [comment]
@prioux , I cannot reproduce that bug, and the filters should be saved after every request to the userfiles controller's `index` action ([userfiles_controller.rb:132](https://github.com/aces/cbrain/blob/679afed1c08c2ce751a99beb3255a0bf2c4cb173/BrainPortal/app/controllers/userfiles_controller.rb#L132)).

Can you reproduce it consistently? If so, can you post here the contents of the `@session` object when the issue occurs?

**Comment by prioux** [comment]
I'll try to find a way to reproduce it consistently tomorrow, now that I know more or less what I was doing. I have to wait until new files 'trickle into' my ReadyToArchive custom filter.

**Comment by prioux** [comment]
Instead of archiving, I'll send the "sync to cache" post, which will allow me if it works to be able to do it again and again, because it won't affect the archiving status of the files themselves.

**Comment by Najmahan** [comment]
Currently, the only advantage of the new Select Tool box is the search box.

Other filters don't work and the tags are not set.

The "All Tools" list should be nevertheless sorted alphabetically.

fsl_sub should not appear in the list of tools as it is a wrapper for submitting batch jobs.

**Comment by glatard** [comment]
I think the "All tools" list is sorted by frequency of use, which is a desirable feature.

**Comment by natacha-beck** [comment]
Can be difficult to understand without any hint, maybe should be alphabetic
(more intuitive), and add a way to sort by frequency ?

What do you think ?

2016-01-19 11:57 GMT-05:00 Tristan Glatard <notifications@github.com>:

**Comment by Najmahan** [comment]
It is a desirable feature only if the user explicitly opts for that feature.

**Comment by prioux** [comment]
I still can't reproduce my bug report of two days ago... :-(

**Comment by natacha-beck** [comment]
@prioux:  Created a summary of this one #318. I have to ignore your bug report about filtration, since we are not able to reproduce this one.
