### ISSUE TITLE
Look for an alternate email-based authentication (Persona will be decommissioned in Nov 2016). 

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#292]
See email below from the Persona mailing list. 
---
Hi Everyone,

When the Mozilla Identity team transitioned Persona to community
ownership, we committed resources to operational and security support
throughout 2014 [1], and renewed that commitment for 2015 [2].  Due to
low, declining usage, we are reallocating the project’s dedicated,
ongoing resources and will shut down the persona.org services that we run.

Persona.org and related domains will be taken offline on November 30th,
2016.

If you run a website that relies on Persona, you will need to implement
an alternative login solution for your users.  We have assembled a wiki
page with additional information and guidelines for migration [3], but
here are the important things you need to know:

Between now and November 30th, 2016, Mozilla will continue to support
the Persona service at a maintenance level:

 * Security issues will be resolved in a timely manner and the services
   will be kept online, but we do not expect to develop or deploy any
   new features.

 * Support will continue to be available on the dev-identity mailing
   list [4] and in the #services-dev IRC channel [5].

 * All websites that rely on persona.org will need to migrate to
   another means of authentication during this period.

Beginning on November 30th, 2016, the Persona service hosted by Mozilla
will be decommissioned:

  * All services hosted on the persona.org domain will be shut down.

  * Mozilla will retain control of the persona.org domain and will
    not transfer it to a third party.

  * Since the privacy of user data is of utmost importance to Mozilla,
    we will destroy all user data stored on the persona.org servers,
    and will not transfer it to third parties.

We intentionally designed Persona to expose email addresses rather than
opaque identifiers, which should ease the transition to other systems
that provide verified email addresses.  You can find guidelines on
alternative login solutions on the wiki [3] and we will continue to
update them over the coming year.  We strongly encourage affected teams
to openly discuss and blog about their migrations on the dev-identity
mailing list  so that others can learn from their experience.

Thank you for your support and involvement with Persona. If you have any
questions, please post them to the dev-identity mailing list.

  Ryan

[1]
http://identity.mozilla.com/post/78873831485/transitioning-persona-to-community-ownership
[2] https://groups.google.com/forum/#!topic/mozilla.dev.identity/rPIm7GxOeNU
[3]
https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers
[4] https://lists.mozilla.org/listinfo/dev-identity
[5] http://irc.mozilla.org/#services-dev

**Comment by prioux** [comment]
I suggest we take out completely Mozilla Persona authentication within CBRAIN

**Comment by glatard** [comment]
I think we should rather replace it by another email-based authentication. Persona will still be supported for the next 10 months, there is time to investigate this issue before it gets urgent.

**Comment by driusan** [comment]
Persona, as a protocol, also doesn't cease to exist, just the persona.org authentication provider.

**Comment by merous** [comment]
It's definitely not high priority right now.
It will become important to have a clear replacement plan in about 5-6 months.

**Comment by prioux** [comment]
For the moment at least I'm removing the support code and libraries.

**Comment by prioux** [comment]
Fixed by #457
