### ISSUE TITLE
New Interface: how do I open the context menu for a userfile, on the index page?

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#293]
I used to be able to right-click (aka menu-click) on a userfile's name in the userfile index page and then select "open in new tab" from the browser's menu. Also the browser provided other useful action right there (copy link location, open in new window etc). Now it's all gone, as it's overriden by the new interface.

I don't think overriding the default browser-provdied menu was a good choice...

**Comment by remibernard** [comment]
This is not a bug; this is the intended behaviour as the new interface tries to mimic what a typical desktop file manager on Windows, OSX or Linux does. This is also how other widely popular online file sharing services (MEGA and Dropbox, for example) work.

AFAIK you can directly open a link in a new tab using the middle mouse button, and you can completely override the menu using a Firefox `about:config` setting; `dom.event.contextmenu.enabled`.

**Comment by prioux** [comment]
No, this is a bug. The new menu is nice and all, but should open only when the pointer is not on a link within the row; on a link, it should show the browser's context menu. The browser menu is where browser extensions can put useful features that the user has configured, and now they're not available.

Myself, I use the context menu extensively: I do "open in new tab" all the time, and "inpect element" too. With the current system we can't even do "inspect element" and we're the developers!

An example on how to do it right is in Redmine itself: go to the issues page and right click on the title of an issue, then rick click elsewhere on the row.

**Comment by prioux** [comment]
Right here on GitHub I've tried to summon a custom context menu, and I've not been able to find a single one anywhere. It seems the GitHub devs have opted never to override it, which I think is a wise decision.

**Comment by remibernard** [comment]
If something is working as designed/planned, then the behavior is not a bug. Nothing was mentioned about keeping the browser's context menu in the UI meetings. Although it *is* a very good enhancement and I'll implement it right away.

As for GitHub and Redmine, note that they do not have file management functionality (not as their core service anyway), unlike MEGA or Dropbox which do use custom context menus more extensively to mimic OS file browsers.
