### ISSUE TITLE
Improved Docker image transfers on clusters

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#295]
Currently, Docker images are transferred from DockerHub to every cluster node. This is how Docker is configured on the clusters, at least on Guillimin, and it is not likely that it could radically change soon (although improvements such as a local Docker index would help). A nice solution would be to save images as CBRAIN files, i.e. cached on each clusters, and start Docker containers from these files. This involves:
1. Pulling the image from DockerHub. 
2. Saving the image in CBRAIN, using the following command:
[root@lm-2r02-n77 ~]# docker save fedora:latest | gzip > /sb/compute_admin/docker_images/fedora-latest.tar.gz
3. Loading the image before running the container (should be done on the execution host, i.e. by the jobs):
[root@aw-4r12-n19 power-stats]# gunzip -c /sb/compute_admin/docker_images/fedora-latest.tar.gz | docker load & docker run -it --rm fedora-latest

I think 1. and 2. should be done by the first job that will use the image. Otherwise, i.e. if an admin has to do this, each image update would require admin intervention. However, that means that there is a way to associate a Docker image name (e.g. fedora:latest) to a CBRAIN file id. To be thought and discussed...

In any case, we could enable/disable this feature using a checkbox in the tool config where the Docker image is defined.

**Comment by prioux** [comment]
I think we could integrate this with the caching subsystem I created for singularity!

**Comment by prioux** [comment]
Yes, the ClusterTask core code has had the ability to pull images and cache them for some time now. Also, the ToolConfig model has attributes so that the admin can configure a cbrain userfile as the tool's image. So... all done.
