### ISSUE TITLE
UI/UE improvement: In the task parameters/summary, present input and corresponding "completed" outputs side by side

### ISSUE THREAD

**Issue by Najmahan** [aces/cbrain#298]
An example:
While running CIVET, CBRAIN creates a task by running CIVET on 12 datasets in each task. If only 1/12 failed, the entire task is labeled as 'failed'. The user wold have a greater experience if upon looking at the summary, he/she can see which one file did not complete.

**Comment by prioux** [comment]
There are already two issues to deal with this. They're in REDMINE, in the project 'CBRAIN Tools'.They are:

https://redmine.cbrain.mcgill.ca/issues/6970
https://redmine.cbrain.mcgill.ca/issues/6971
