### ISSUE TITLE
No workdir size after removal

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#30]
After deleting workdir from tasks, the portal has a blank entry for the size, same behaviour as if the Portal could not access the workdir.
Is that the most relevant behaviour, should indicate "0" or "None".
Add

- Updated by Pierre Rioux almost 3 years ago

The table entry just has a NULL for the size column when there is no
workdir present, or if the workdir exists but the size has not
yet been computed. We can't really tell which is which, so that's
why I left it blank. What do you suggest?

- Updated by Pierre Rioux almost 3 years ago

Actually, there is a way to distinguish between the two.
So, what labels do you want?

- Updated by Marc Rousseau over 2 years ago

O for knowing the size is 0,  or NA when the system cannot access it.

**Comment by remibernard** [comment]
The method [`remove_cluster_workdir`](https://github.com/aces/cbrain/blob/9b300db3cff650c4d6404a91c70e77bdd4766c3b/BrainPortal/app/models/cluster_task.rb#L1588), which handles removing task workdirs, does not seem to have any error handling:
```ruby
    # ...
    self.addlog("Removing workdir '#{full}'.")
    FileUtils.remove_dir(full, true) rescue true
    self.class.rmdir_numerical_subdir_tree_components(self.cluster_shared_dir, self.id) rescue true
    # ...
```

As such, I doubt it is possible to differentiate between a deleted workdir and one that cannot be accessed (without modifying `cluster_task`, of course), as `remove_cluster_workdir` will set both `cluster_workdir` and `cluster_workdir_size` to `nil` even if the removal fails.

Pierre's comment does not seem to address the issue; while it is correct that we know if the workdir exists even if its size cannot be computed, this does not apply after deletion as we do not know if `remove_cluster_workdir` successfully removed the workdir; `cluster_workdir` is being set to `nil` regardless of whether or not the workdir was actually removed.

**Comment by natacha-beck** [comment]
@prioux: Can you take a look to the comment of Remi.

**Comment by remibernard** [comment]
I had a quick discussion with Marc about this, and this is apparently no longer relevant.
