### ISSUE TITLE
New File Manager UI: Rename leads to error message

### ISSUE THREAD

**Issue by merous** [aces/cbrain#301]
A rename operation leads to this message (however the rename is successful):

Error sending background request: 
HTTP 200 OK
The CBRAIN administrators have been alerted about this problem.

**Comment by remibernard** [comment]
As strange as it may seem, while the request succeeds, this is a server-side issue: the server returns an empty response to the client if the update succeeded, yet marks it as XML, which is incorrect as no content at all is not a valid XML document.

The correct fix would be to force Rails to change the Content-Type, but it looks ugly no matter what; this is an issue with Rails and should be handled within the framework.

**Comment by prioux** [comment]
I'll find a fix

**Comment by natacha-beck** [comment]
@remibernard : I think it's fix in #314 ? No ?

**Comment by remibernard** [comment]
@natacha-beck; more like a workaround than anything else.
