### ISSUE TITLE
New File Manager UI: Select all box does not trigger dynamic menu

### ISSUE THREAD

**Issue by merous** [aces/cbrain#303]
After doing a select all, only the two initial options (Launch, Upload) are available.

**Comment by remibernard** [comment]
I cannot reproduce this. Which browser version are you using?

**Comment by merous** [comment]
I'm on a Mac:

- Safari 9.0.3 
- Tristan had the same issue on his Linux machine. (Chrome ?)

Firefox 44.0 and Chrome 48 seem to work properly.

Please re-assign to prioux after feedback.

**Comment by merous** [comment]
Well.... Problem cannot be reproduced consistently.

The erroneous behaviour has gone away after a browser re-launch (Mac - Safari), and Tristan cannot replicate on Linux today.

Closing ticket for now.  
Will open a new ticket if the issue re-emerges.
