### ISSUE TITLE
Launch Task of the select tool overlay bug.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#336]
It redirect to index page, don't know if it should be the case. 
I think: 
1) Should stay on the overlay. 
2) Should redirect on the new task page. 
3) Should definitively not put the launch at the bottom of the index table. Like this: 
![screen shot 2016-02-18 at 3 58 25 pm](https://cloud.githubusercontent.com/assets/777590/13157993/b60bb0d6-d658-11e5-9524-d10584012c7d.png)

**Comment by prioux** [comment]
The issue doesn't explain how this is produced.
