### ISSUE TITLE
Create DataProvider class to model a Bourreau's 'gridshare' directory.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#34]
Each Bourreau is configured, on the cluster side, with a
directory called the 'shared work directory' (a.k.a. 'gridshare')
which is where each task's work directory is created.

I'm thinking it would be great to write a data provider
class to model this gridshare directory, where each of the
registered file would represent the work directory
of a task. Add attributes to the Userfile and CbrainTask
models and we can link the IDs with a 'has_and_belong_to'
association. The userfile class would be fixed to a new
model TaskWorkDirectory, a subclass of FileCollection.

This new feature could help tremendously with the problem
of implementing an archiving mechanism for tasks (Issue 1212).

Make sure the new design for the task directory
hashing feature is complete, first (Issue 2070).

Related: 1212, 2070, 2258, 2358 || #33 , 2372.

**Comment by prioux** [comment]
This is no longer necessary, and browsing work directories as a data provider doesn't seem that useful anymore.
