### ISSUE TITLE
Select-all checkbox is off by a few pixels

### ISSUE THREAD

**Issue by remibernard** [aces/cbrain#349]
Data provider browsing page, Chromium 49.0.2584.0 on Windows.

![off](https://cloud.githubusercontent.com/assets/12155323/13479347/2c977046-e0a4-11e5-8412-fb9e5e1d8141.png)

Only happens to this page. Other tables (userfiles, tasks, tools, etc.) look fine (the checkboxes are aligned).

**Comment by prioux** [comment]
It's caused by a race condition in the Windows NT kernel thread dedicated to rendering checkboxes.
