### ISSUE TITLE
Allow 'restart' of 'Failed On Cluster' tasks

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#35]
If the failure 'Failed On Cluster' is caused by invalid params,
the user cannot edit the page and restart the task
at 'setup'.

**Comment by prioux** [comment]
Yep, I guess this is the lifecycle of a task in that particular state: the 'recover' path will re-submit the task (including ivoking cluster_commands() and building the launch script) but will not run the setup() code.
