### ISSUE TITLE
Upload file with space raise an ugly error message. 

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#365]
When a user tries to upload a file that file name  contains white-space the platform raises an error, and the following flash message appears:

> 
> Error sending background request:
> HTTP 422 Unprocessable Entity
> The CBRAIN administrators have been alerted about this problem.

This should be more explicit.

**Comment by crocodoyle** [comment]
Working on this bug now, fyi @prioux

**Comment by prioux** [comment]
Okay thanks.

**Comment by prioux** [comment]
Closed, thanks Andrew.

**Comment by prioux** [comment]
Wasn't this issue closed by #421 ?
