### ISSUE TITLE
The DataProvider index page should not do a "is_alive?" check automatically.

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#368]
The entries in the table should have a "check" button that triggers the check for that data provider.
Maybe add a "check all" button to get the current behavior.

**Comment by crocodoyle** [comment]
Can I work on this?

**Comment by crocodoyle** [comment]
Is it particularly important that the data providers be checked sequentially, or can they all be checked simultaneously?

**Comment by prioux** [comment]
It's better one at a time, otherwise if n DPs out of m are inaccessible, they jam Rails instances and decrease the site's availability

**Comment by prioux** [comment]
Fixed, thanks.
