### ISSUE TITLE
Some glitches with BrainBrowser

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#369]
1. "Threshold" text box and slider overlap.
   ![screenshot from 2016-05-11 10-17-46](https://cloud.githubusercontent.com/assets/5174953/15184022/a32bb746-1761-11e6-8b6d-da0bd61907be.png)
2. 4D images are not properly displayed (cannot go through the t dimension)
   ![screenshot from 2016-05-11 10-19-42](https://cloud.githubusercontent.com/assets/5174953/15184101/e49f6cae-1761-11e6-86d0-c527052fd416.png)

**Comment by natacha-beck** [comment]
Close https://github.com/aces/cbrain-plugins-neuro/pull/51

**Comment by natacha-beck** [comment]
Always buggy for the overlapping part in firefox.

**Comment by crocodoyle** [comment]
I tried to reproduce the slider overlap in Firefox and it looked fine to me. Definitely less spacing than Chrome but it was still OK.

I don't have any 4D data so I can't test the other issue.

**Comment by prioux** [comment]
Fixed in plugins.
