### ISSUE TITLE
Create tests for Boutiques

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#382]
Create a set of tests for the Boutiques code generator.

- [ ] Write a test application (e.g. a bash script) that uses all the features in a Boutiques descriptor, prints information about its parameters and returns an error when the syntax of the command line is not correct. For instance, "test.sh -a" would print "INFO: Flag 'a' is active" and return 0, while "test.sh -b" would print "ERROR: input 'b' requires a string" and return a non-zero exit code. 
- [ ] Write a JSON descriptor for this test script. 
- [ ] Write test assertions, including but not limited to:
- The JSON descriptor validates
- CBRAIN can generate a tool from it
- The generated CBRAIN tasks succeeds or fails depending on specific test inputs. For each of the test inputs, submit a task to CBRAIN through the API with the expected final status (Failed or Completed) in the description field. The format used for the test inputs and the code to submit the tasks could be based on a more general version of https://github.com/glatard/cbrain-tests-fsl-melodic that was developed specifically for FSL Melodic. Ideally, the test inputs shouldn't contain any CBRAIN-specific information. CBRAIN-specific information (e.g. tool config to be used) should be in a configuration file or parameter of the test submission script. 

The test script, JSON descriptor and test inputs could be uploaded and documented in the Boutiques github repo. The (Ruby) script to run the tests in CBRAIN should be in CBRAIN's repo. In a longer-term, this script could be generalized to test any tool in CBRAIN (not just the Boutiques test application).

@natacha-beck may have some ideas on how to make this fit in the CBRAIN testing framework.

**Comment by ttaa9** [comment]
So we decided to something like: (1) check json descriptor validates, (2) check local script behaviour, (3) test behaviour in cbrain via local qsub scripts, and (4) run some tasks via the cbrain api, should it be present.

Could you expand a little on how (3) should work (and perhaps which methods/classes it should use)?

**Comment by glatard** [comment]
This is what I would do:

```
t=CbrainTask::FslBet.new # Change to the class that implements your tool.
t.params=Hash.new
t.params[:inputfile_id]=2   # Assign all the required parameters.
t.cluster_commands # write these commands in a bash script, run the script, check the exit code. Be careful, method 'cluster_commands' is only available Bourreau-side.
```

**Comment by ttaa9** [comment]
@prioux has suggested we might not need to use the api; we could instead test the generated methods individually.

**Comment by glatard** [comment]
@ttaa9 why not but this might get tricky to write the proper tests, especially for Bourreau-side methods. Ultimately, what we want to test is that the tools run properly, which was the initial motivation for using the API and actually running the task. I suspect that testing the methods individually will result in mimicking what a complete task execution does, most likely less accurately. It may also be much more difficult to write tests for each of the individual methods than for the global task.

**Comment by ttaa9** [comment]
I agree that it tests some things that are hard for me to test in the isolated unit tests. I am just wondering if there is a way to do so without the api, as currently other tests do not require it (so it would not be able to run like the rest of the test suite) unless we just have the api there all the time. Also, the tests are already really slow even without the api (compared to the regular spec tests).

**Comment by glatard** [comment]
then a good start would be to create the cluster commands, write them in a script, and run the script to check that the generated command is working. See code sample above. You could test various parameter combinations in this way. This wouldn't test that input/output files are correctly transferred though.

**Comment by ttaa9** [comment]
So, it turns out to be possible in the rails rspec to create a Bourreau with mock data providers, users, groups, and userfiles. I am able to successfully test that the output files are renamed in the save_results cluster task method when there is a collision, for example. (Although it took me longer than expected). I agree it is not end-to-end still though.
