### ISSUE TITLE
Update project switching menu

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#395]
The top `switch project` menu is ugly and a bit confusing.

**Comment by crocodoyle** [comment]
How's this?
![screen shot 2016-06-22 at 10 22 08 am](https://cloud.githubusercontent.com/assets/345229/16270154/4b8af7cc-3863-11e6-9a75-0e5f8fdbdeda.png)

**Comment by prioux** [comment]
Fixed by combining Andrew's changes and a few mods of my own.
