### ISSUE TITLE
Handling of output files in Boutiques

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#396]
Before registering an output file, check if the file name already exists. If it does, append the task id to the file name (e.g. "image.nii.gz" becomes "image-123.nii.gz") so that the file isn't overwritten.

**Comment by prioux** [comment]
How about always appending a uniqe identifier after the output file name?

Objects of class CbrainTask have many many methods for building such identifiers:

https://github.com/aces/cbrain/wiki/Task-Helpers#1-cbraintask-model-helpers

The most commonly used is `bname_tid_dashed()` ...

**Comment by remibernard** [comment]
Output files can be named by the user via substitution keys; it would be weird to append something to the name if the user explicitly specified the output filename.

It makes sense if there's a collision, but not in the general case.

**Comment by prioux** [comment]
What about the other extreme? If the output exists, crush it. Period.

**Comment by remibernard** [comment]
The user might not know that the output already exists, especially if the file is owned by a different user on certain data provider types.

Renaming collisions isn't an especially elegant solution UI and design wise, but it seems like a safe bet and only strays away from what the user expects when the exceptional case appears.

**Comment by glatard** [comment]
+1 for using a CbrainTask method to rename the file only in case of name collision, with a warning in the task log.

**Comment by ttaa9** [comment]
For some people used to being warned when their 'copy' will overwrite something, this might be better. Although, some programmers might actually expect and want it to overwrite the files (e.g. for testing different parameters you may only want to keep the output files of one). But then their only inconvenience is having to delete things I suppose.
