### ISSUE TITLE
Refactor SmartDataProviderInterface's method that selects real provider

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#400]
SmartDataProviders, when instantiated, keep inside themselves an instance variable `@real_provider` assigned to a data provider object which will implement the functionality. That real provider is either a network provider or a local provider, depending on run-time context.

The way the choice is made is in a method called `select_local_or_network_provider` ; the code of this method could be refactored and improved quite a bit. Right now it builds two 'real' providers then assigns it to `@real_provider`. It should build just the one it needs by making the choice of context right at the top.

**Comment by crocodoyle** [comment]
I'm not sure how to test that my fix worked. I created a SmartDataProvider successfully, and it's online and alive.

**Comment by prioux** [comment]
Try to force it to switch to one provider type ot the other by switching back and forth the attribute "remote_host", then in the console realoding the object and checking the type of what is returned by the method real_provider(). Make sure you get two diff types.

**Comment by crocodoyle** [comment]
Can be closed

**Comment by prioux** [comment]
Indeed!
