### ISSUE TITLE
Fix tests: raise_error() to always receive an argument

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#407]
We have many places in our tests where we check for raise_error() without specifying which error.

All of them should be changed to `raise_error(CbrainError)` (or another approriate error class).

**Comment by crocodoyle** [comment]
When I run the tests, I get the following warning: 
DEPRECATION WARNING: ActionController::UnknownAction is deprecated! Use ::AbstractController::ActionNotFound instead. (called from block in included at /Users/adoyle/cbrain/BrainPortal/lib/exception_helpers.rb:32)

Should I change the ActionController::UnknownAction to AbstractController::ActionNotFound?

**Comment by prioux** [comment]
That should be a separate issue, because it's related to the old code base of the will_paginate gem.

**Comment by crocodoyle** [comment]
can be closed

**Comment by prioux** [comment]
@crocodoyle OK, will close the issue now; if the DEPRECATION WARNING above is still there, maybe create a new issue for it?
