### ISSUE TITLE
Replace "E-mail" with "email"

### ISSUE THREAD

**Issue by crocodoyle** [aces/cbrain#408]
Throughout the code, where messages that say that an email has been sent to the user, the word "E-mail" is used. This is an older convention, and it should be changed to "email".

**Comment by prioux** [comment]
Yes, and many other things too... maybe at some point we should do an entire week of 'style' review here. Let's build a list here, while we're at it:

* E-mail -> email
* etc (to be edited)

**Comment by crocodoyle** [comment]
"staggered_loader" isn't really staggered, it's just sequential... maybe add that to the list

**Comment by crocodoyle** [comment]
can be closed
