### ISSUE TITLE
Robustness of some view helper code

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#414]
I get this from time to time:

```
Exception: NoMethodError: undefined method `-' for nil:NilClass
/home/cbrainsys/CBRAIN/BrainPortal/app/helpers/userfiles_helper.rb:72:in `file_link_table'
```

(In the exception log)

I think it's just a bit of robustness that needs to be added, might be triggered by users editing the URL.

**Comment by crocodoyle** [comment]
I can't reproduce this

**Comment by prioux** [comment]
I fixed it myself a few weeks ago.
