### ISSUE TITLE
Export as CVS link doesn´t work.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#429]
In the Userfile index page, we have a link in the `More`  menu called `Export as CSV`.
This link should allow the user to export the index table in CSV format. But now this link make nothing. To trigger the download you can directly acces the `userfiles.csv` for example `localhost:3000/userfiles.csv`

**Comment by crocodoyle** [comment]
It appears to work in Chrome on a Mac.

**Comment by natacha-beck** [comment]
It was an issue on firefox only. Fixed by #439
