### ISSUE TITLE
Add support for CbrainFileList userfile model

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#436]
New Userfile model CbrainFileList < CsvFile

* content: csv text file, comma separated, newline terminated
* first column is ID of a CBRAIN file
* other columns are useful attributes to view (name, owner, project etc... to be determined, but list to be fixed)
* ID of 0 is supported to represent an empty slot in the list
* add userfile viewer code for the list, shown as pretty table. Does not have to be as fancy as userfile index page of course.
* supply method to validate content
* supply method to instantiate list of userfiles (take into account user access privileges)
* add new button in userfile index page to create such a list based on selected files (with requester for new name?)

**Comment by glatard** [comment]
Related to #160.

**Comment by prioux** [comment]
See #441
