### ISSUE TITLE
DB reconnection

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#44]
With the following option in database.yml, rails apps will try to reconnect to the DB in case of connection issues (typically leading to the following error message: "Mysql2::Error: MySQL server has gone away"). This is useful when the network between the Bourreau and the Portal is shaky.

reconnect: true

Original Author: glatard

**Comment by prioux** [comment]
It's a neat feature but probably unnecessary:

* if the tunnel is down, the reconnect won't work anyway
* if the tunnel is up, the reason the DB connection was closed was probably something serious that needs investigating anyway

I cannot think of a circumstance in the past few years where `reconnect = true` would really have helped in our production system.
