### ISSUE TITLE
No warnings when removing a task can't also remove the workdir archive

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#45]
If a Bourreau doesn't have access to the DP where a task's archive is kept, and the task is deleted, no warning is sent. The task's archive will keep being registered in the DB.

Possible solutions:

1- have the portal remove them? (Prob: time taken, portal might be prevented to access this DP too)
2- warn user, don't do anything else
3- warn admin instead
4- refuse destroying task, tell user

Comment by Marc: 
I would tend to use option 3.
CBRAIN could maintain a list of "things that should be checked by an admin"?

**Comment by prioux** [comment]
Possibility: tag the file with a special system tag?

**Comment by prioux** [comment]
Fixed in #832
