### ISSUE TITLE
Update the params_errors() API to match current Rails errors() API

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#450]
We have a wrapper class `PortalTask::ParamsErrors` which is supposed to provide an API to record errors in a task's params using the exact same methods as for standard ActiveRecord attributes (which is done with the errors() method returning an ActiveModel::Errors object). However it seems many of the methods in ActiveModel::Errors have changed and so our wrapper is no longer in sync. For instance, methods such as `on()` and `on_base()` no longer exist. Maybe new ones exist too.

We need to update it our class so that its API become identical again.

**Comment by crocodoyle** [comment]
There are lots of new methods. Do we want to include them all?

![screen shot 2016-09-14 at 11 51 01 am](https://cloud.githubusercontent.com/assets/345229/18519332/93bdc5f6-7a71-11e6-98f6-a6a87e176e23.png)

**Comment by prioux** [comment]
Yes, why not? I think they're all probably going to be quite easy.

**Comment by crocodoyle** [comment]
can be closed

**Comment by prioux** [comment]
By Jove, you're correct my good fellow.
