### ISSUE TITLE
Boutiques task preview is not readable when file names are too long.

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#465]
See screenshot:
![screenshot from 2016-08-19 09-35-25](https://cloud.githubusercontent.com/assets/5174953/17811371/5d67d680-65f0-11e6-9120-44ccd3b4cbd3.png)

**Comment by ttaa9** [comment]
It seems to be fixable with one line of css, assuming you just wanted it to wrap

**Comment by prioux** [comment]
Merged.
