### ISSUE TITLE
Do NOT store active record objects in class instance variables!

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#47]
Do no store active record objects in class instance
variables. It's often done as a 'caching' mechanism,
but they do not ever get reloaded, and their relationships
become stale. An example of such a bug fix can be seen
in commit: baa25daa41357a947bfd4d821c0f66956c3e084b in file cbrain_task.rb . 

See also issue 4454 .

**Comment by prioux** [comment]
It think we're ok. I did a quick scan of all controllers and all models; the only cases I've seen were for a few static 'singleton' objects, like the admin user, the everyone group and the scratch DP.
