### ISSUE TITLE
Tasks index page missing column when bourreau offline, in batch mode

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#473]
In the tasks index page, batch mode, when a bourreau is offline and one try to expand a small batch of tasks, the rows that appear are all badly aligned because of a missing TD element where the checkbox would appear (the checkbox is properly not shown, but an empty TD shoudl be there instead). This happens for small batches (with a + sign). See screenshot for the batch of RPM tasks:

![screen shot 2016-09-02 at 15 16 12](https://cloud.githubusercontent.com/assets/777588/18215664/43fe3f28-7120-11e6-9ea4-7461275daa8a.png)

**Comment by crocodoyle** [comment]
Can be closed
