### ISSUE TITLE
CSRF check failures can redirect to a POST

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#477]
If a POST is performed with a bad CSRF, the session records the original page to `:return_to` and the user is returned to the login page. When authenticating successfully, the `:return_to` is sent as a GET redirect, which fails.

To test:

* Go to userfiles index page
* In the console, find the current session object under `CbrainSession`, and change in its `data` the value of the key `"_csrf_token"`.
* Do an action that triggers a POST (such as select a file to compress or uncompress
* You'll be redirected to the login page
* Enter login password
* You'll be redirected to a wrong URL (e.g. `/userfiles/uncompress`)

**Comment by crocodoyle** [comment]
Can be closed
