### ISSUE TITLE
CSRF failures on login page can still allow user to log in, but CbrainSession is not properly set up

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#478]
Use a procedure almost identical to the one described in #477, change the CSRF token in the session just before logging in. Then examine the session object (which will be a different one in the DB!), and the two attributes `:user_id` and `:active` will be both blank, even though the session is actively being used (because the authentication mechanism use the `:user_id` field INSIDE the `data` attribute).

**Comment by crocodoyle** [comment]
Can be closed
