### ISSUE TITLE
Bourreau attribute updated, yet not logged

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#500]
Tiny bug.

I edited a bourreau's config and changed the value for the attribute for "Maximum total number of active tasks", but the object's log did not record the change.

**Comment by crocodoyle** [comment]
This looks like it's because that field is part of the `meta` hash. Do we want to log the provenance of the metadata fields in the Bourreau object's log?

**Comment by prioux** [comment]
Ah OK, I though it was a normal attribute. Eventually we'd like to log changes in meta data too, I guess, for chosen meta data keys. But we have no framework for that, and the meta data store doesn't provide a way to check was is about to change (unlike ActiveRecord).
