### ISSUE TITLE
Whitelist attributes for models when sent by APIs

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#511]
Some of our models have attributes that shouldn't be seen through APIs.

Right now we have clumsy controller code to remove these attributes (e.g. for DPs see the constant API_HIDDEN_ATTRIBUTES) before sending them off.

A better solution is for each model to have a whitelist of attributes that are API safe. Then a generic model instance method .for_api() would produced a slimmed-down object. In the controller we'd get

```
render :json => @obj.for_api
```

**Comment by prioux** [comment]
Already part of my next PR.

**Comment by prioux** [comment]
This is in my branch swagger_api by the way. I've only started going model to model and preparing the whitelists.

**Comment by crocodoyle** [comment]
The initial model whitelisting is done, but will have to be reviewed. This issue could probably be closed

**Comment by prioux** [comment]
I'll close once I've had a look at the white lists.
