### ISSUE TITLE
Adjust log viewer filtering rules

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#515]
The 'view log' feature has a few checkboxes to filter out log lines, such as "Load", "CACHE", "Rendered" etc. These use to match particular log line patterns, but the format of the Rails log has changed slightly since then and they are not up to date. SQL lines are now looking like:

```
  (0.2ms)  SELECT COUNT(*) FROM `users` 
```

and I don't see any of the 'AREL' lines anymore.

Update the list of patterns and filtering code.

**Comment by crocodoyle** [comment]
can be closed
