### ISSUE TITLE
Boutiques tools with inputs that don't have the 'optional' propery defined crash.

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#527]
If the optional property is not present, it should be assumed that the input is not optional, as it is meant in JSON.

The tool currently crashes with the error message attached. 
![screenshot from 2016-10-24 14-08-42](https://cloud.githubusercontent.com/assets/5174953/19657857/c449f612-99f3-11e6-86ae-59e3793fed8c.png)

**Comment by natacha-beck** [comment]
Fix by https://github.com/aces/cbrain/pull/550.
