### ISSUE TITLE
Add ExitOnForwardFailure to SSH options for control masters

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#545]
SSH control masters for Bourreaux would benefit from using the `ExitOnForwardFailure` option.

**Comment by crocodoyle** [comment]
There's a branch in my fork where I attempted to implement this, but I have no idea how to test it. I don't think it broke anything though; I tested by simply stopping and starting a Bourreau.

https://github.com/crocodoyle/cbrain/commit/23abf2c5bf60042f928023810db329888dbee8b3

**Comment by prioux** [comment]
I looked at it, it's wrong, the option must be set in the proper place in the code, in `ssh_shared_options()`. Also your code is potentially buggy (you didn't leave spaces around your option, it could get concatenated with previous or next arguments)

**Comment by prioux** [comment]
We will postpone this feature as the option is not supported on all versions of `ssh`. That is the case on our old CentOS servers, but it might be a common situation out there depending on when the SSH dev team introduced the option.

**Comment by prioux** [comment]
Let's revisit this in 2020.

**Comment by prioux** [comment]
I just couldn't wait for 2020.

**Comment by prioux** [comment]
Fixed by #840 

Note: the check will only work in a strict IPv4 env, it seems when IPv6 is also available, SSH is still able to 'listen' to the port even when another process has allocated it, and so doesn't exit.
