### ISSUE TITLE
Implement Remote Resource command 'stop_yourself'

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#55]
A remote Rails application (such as a Bourreau)
is currently stopped by sending it a signal (SIGTERM
by default) from an external process (the ruby script
cbrain_remote_ctl when remote control is configured).
A new command 'stop_yourslf' on the control channel
could do the trick even more cleanly: the remote
resource receiving it could:
- stop its workers
- stop the SSH master channels for the data providers
- stop the SSH master channels for the
- Bourreaux (N/A for the Bourreaux themselves)
-  send itself a TERM signal using spawn_fully_independent()

Related: 690 || #54 
#### Comments:
- Updated by Marc Rousseau almost 5 years ago

Although cleaner, I feel this is a low-priority back-end improvement which can be administered manually (as we do currently).

**Comment by prioux** [comment]
Fixed in #832
