### ISSUE TITLE
AccessProfiles are not applied at user creation time

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#555]
The IDs of the profiles are set, but they groups list is not adjusted.

It is fortunate that as soon as the user connects and modifies any aspect of his account (including resetting the password), the access profiles groups will be applied as a side effect. But it should really be done at account creation time.

**Comment by crocodoyle** [comment]
Note to self: this, and other Access Profiles issues, can be solved by calling `apply_access_profiles` with the :before_save callback in the User model.

**Comment by prioux** [comment]
It would be best to wrap the method inside a separate one that is registered as the callback:

```ruby
before_save :adjust_ap

def adjust_ap  # find better name
  apply_access_profiles
  true
end

That's because apply_access_profile was not originally designed to be a callback, so no guarantee about its return values etc.
