### ISSUE TITLE
Use Boutiques' localExecutor.py to run Boutiques tools

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#564]
This would simplify the synchronization between Boutiques schema and implementation in CBRAIN. See (initial) discussion in https://github.com/boutiques/boutiques/issues/51

**Comment by natacha-beck** [comment]
I think it can be closed when  #1130 will be done.

**Comment by natacha-beck** [comment]
Done by the new Boutiques integrator in CBRAIN.
