### ISSUE TITLE
Portal to answer to info(:ping) action without authentication.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#57]
That way, several distinct portals can report about each other's uptime.
E.g. the BrainPortal 'CBRAIN' can give out information about 'MindPortal'.

**Comment by remibernard** [comment]
The current implementation of [`ping`](https://github.com/remibernard/cbrain/blob/master/BrainPortal/app/controllers/controls_controller.rb#L43) already answers without authentication (XML API only).

```
$ curl 'https://portal.cbrain.mcgill.ca:4000/controls/ping' -H 'Accept: application/xml'
<?xml version="1.0" encoding="UTF-8"?>
<RemoteResourceInfo>
 ...
</RemoteResourceInfo>
```
