### ISSUE TITLE
Swagger Bugs

### ISSUE THREAD

**Issue by crocodoyle** [aces/cbrain#573]
There are several issues with the current Swagger implementation:
1. Many actions do not return expected JSON documents with good HTTP status when they fail.
-`/session/create` doesn't even respond if you enter the wrong password
-Many actions that take an id parameter respond with an HTML message if the ID doesn't exist. This should be fixed in the ApplicationController
-There are javascript errors on the swagger page.

**Comment by crocodoyle** [comment]
I think that the route for the API should be `/api` and not `/swagger`, as we are not tied to the swagger framework and may just confuse people.

**Comment by prioux** [comment]
It is absolutely a Swagger spec we are providing, when downloading it. The JSON document IS swagger, nothing else.

**Comment by crocodoyle** [comment]
I don't see why people will download the .json file. The more useful aspect is the web page which documents the REST calls. The API.

**Comment by prioux** [comment]
The JSON file is what they use to build librairies in other languages.

**Comment by prioux** [comment]
E.g. http://swagger.io/tools/

**Comment by crocodoyle** [comment]
Pierre Rioux noticed that some of the javascript errors are related to jquery versions. Some of the Swagger code (which we don't use, I don't think), requires jquery 1.9, and we are currently on version 1.8. The bootstrapification will upgrade jquery to version 2.2
