### ISSUE TITLE
Disallow registered files on SFTP servers

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#58]
1- When registering files into CBRAIN, user can only move or copy files, no file should be registered from the SFTP and stay there.

2- When user wants to put back data to the SFTP, he/she should only be able to create an unregistered copy. Moving it leads to a registered file in SFTP and is confusing (they delete it, etc...).
If user wants to put results in SFTP and then delete the CBRAIN copy, he/she will have to do it in 2 operations, that is fine.

**Comment by prioux** [comment]
I'm closing this as users sometimes want the ability to move registered files to the SFTP side and yet still access them, launch tasks, etc.
