### ISSUE TITLE
Label for task recovery button is full of junk

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#588]
For a task in status `Terminated` I can see these buttons: check out the 'recovery' button.

![screen shot 2017-01-07 at 12 43 56](https://cloud.githubusercontent.com/assets/777588/21743798/c87dbccc-d4d7-11e6-9173-ced0e76c5981.png)

This bug was introduced by https://github.com/aces/cbrain/commit/b39dbc2a92102a2fac98bfb2ea35e81e3c82ab9f

There should be no error recovery for Terminated tasks.

**Comment by prioux** [comment]
Also, it seems the 'Restart' buttons have been enabled for states where it's not allowed; see line 78 which says:

```ruby
if CbrainTask::FAILED_STATUS.include?(@task.status) or @task.status =~ /Completed|Terminated|Duplicated/
```

**Comment by crocodoyle** [comment]
These buttons didn't exist before. According to the diagram, only Completed tasks can be restarted. Is this correct?

**Comment by prioux** [comment]
Restart is allowed only for 'Completed', 'Terminated', and 'Duplicated'.

**Comment by crocodoyle** [comment]
Can be closed
