### ISSUE TITLE
New options: use persistent SSH master or not for DPs

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#59]
Each Ssh DP should have an option: use persistent SshMaster
or not (default: yes)

Each Bourreau should have an option: use persistent SshMaster
for DPs or not (default: no for Bourreaux, yes for Portals).

**Comment by prioux** [comment]
This could be combined with the option ControlPersist as described in #281

**Comment by prioux** [comment]
I'm closing this too. We haven't had any problems opening closing and reopening ssh connections for each transaction yet.

**Comment by prioux** [comment]
Actually, I want to investigate further.

**Comment by prioux** [comment]
Done in #844
