### ISSUE TITLE
Several issues with the DP consistency validator

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#593]
* Separate columns for the type of issue and the instance of the issue (e.g. 'Missing File', 'abc.txt'),
* More filtering in the columns (by user, by action, 
* Fixing operation to happen in background (with tracking in the process command line, see how $0 is modified elsewhere)
* For VAULT DPs, errors are reported for the directories of the user vaults themselves, and these are not errors.

**Comment by natacha-beck** [comment]
> Another bug: when switching page, the report DP is accessed and the full report is regenerated anew because the GET option `?reload=true` is added to the links! The reload option shoudl be implemented as a POST anyway.

Seems to be done: 
https://github.com/aces/cbrain/blob/master/BrainPortal/app/views/data_providers/report.html.erb#L29

**Comment by prioux** [comment]
Closed by #918
