### ISSUE TITLE
Signups improvements

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#596]
We need a better way to identify signup records that have been dealt with successfully:

* be able to mark them as 'ignore' forever, so that the 'Approve' link stop nagging us
* be able to recognize that the account has been created but with a login name different from the one in the signup record (so that the 'Approve' link disappear too)

There are no official links (association) between these models and I'd like it to stay that way, so maybe we can improve the account creation mechanism to mark the signup record even when the login name is different, by carrying the signup_id in a hidden field in the account creation form.

**Comment by crocodoyle** [comment]
Can "ignore" forever just be "delete"?

**Comment by crocodoyle** [comment]
I have implemented a "hide" functionality to hide signups.

For the second point, I'm not sure I understand the use case. Do we want to be able to associate a User to a Signup, or the other way around? If it's both, why don't we just make it a one-to-one association?

**Comment by crocodoyle** [comment]
This list could be use to validate institutional email addresses (thanks for finding it @jlurie):
https://github.com/Hipo/university-domains-list

**Comment by glatard** [comment]
That list doesn't have `inria.fr` and neither does it have `cnrs.fr` while CNRS is the [largest fundamental science agency in Europe](https://en.wikipedia.org/wiki/Centre_national_de_la_recherche_scientifique). Also, who tells you that this list only contains "institutional" domain names? Basically, why would you trust that "Hipo" Github account? I'm not sure why you guys want to go into this but I can see troubles coming...

**Comment by prioux** [comment]
Yes, I think we can keep this list around for manual checking, but I don't want it integrated automatically in CBRAIN. Especially since it doesn't seem to be complete, and there's the matter of trust, as Tristan points out.

**Comment by prioux** [comment]
Also, the lists include things like "Oral Roberts University" and "Liberty University", institutions that are not accredited by government organizations (they are accredited by fake religious organizations to pretend to be respectable).
