### ISSUE TITLE
Task show page should provide link to all tasks in the same batch

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#614]
When a task is part of a batch, it would be nice to have a link in that task's show page that sends back to the task index page with a filter set for just the tasks in the batch.

**Comment by blackknight75** [comment]
@prioux I would like to take a shot at this if you dont mind.

**Comment by prioux** [comment]
Okay, go right ahead. It should be pretty easy, my only concern is that the helpers we have that might do the trick are not super easy to understand. Thanks!

**Comment by uzorjchibuzor** [comment]
Is this issue still open?

**Comment by prioux** [comment]
Yes.

**Comment by uzorjchibuzor** [comment]
Okay, I will take a stab at it. Thank you
