### ISSUE TITLE
BrainPortal has a site_id that is barely used

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#626]
Not sure what it is for. See alse #454 !

**Comment by shots47s** [comment]
1. Why is it there?
2. Can it be removed?
3. If yes, remove it.

**Comment by natacha-beck** [comment]
After discussion with @prioux  the issue is related to `site_affiliation`

**Comment by natacha-beck** [comment]
@prioux can you confirm that this issue can be close since it seems to be done by #876. 
And BrainPortal is a remote_resources, and a remote_resources do not have a site_id or a site associate. So we can close this one. Can you confirm ?

**Comment by prioux** [comment]
Yes it van be closed, it was handled in your PR.
