### ISSUE TITLE
Boutiques descriptors always configure themselves on all available Bourreaux

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#632]
This is really annoying, but as soon as a boutiques descriptor is installed on a Bourreau, when it boots up it creates for itself a tool config, even if the admin doesn't plan to make that tool available on that bourreau. All tools must always be present as plugins on all bourreau for single-table inheritance to work in the tasks table, so that means I must copy all the descriptors everywhere. My only options is to change the group of the tool configs to limit their visibility so that users can't launch them. 

This greedy auto integration needs to be rethought.

**Comment by glatard** [comment]
I'd say the fundamental issue is more why all the tools have to be installed on all Bourreaux. Perhaps the Bourreaux could instead rescue from exception when they find a tool that they don't know. It makes the whole system very brittle: just create a dummy task object and you kill all the Bourreaux. Boutiques tools only create a ToolConfig when Docker is declared available. So if Docker is available and the plugin is installed, why wouldn't we create a ToolConfig?

**Comment by prioux** [comment]
There's no way to no 'install' the tools on all Bourreaux; it's important that the Ruby classes exist when accessing the tasks table, because otherwise Rails' single table inheritance will make the app crash. It's not a prob that we can patch easily in CBRAIN. And it's not fundamentally a problem for the tools to be there, as long as the toolconfigs themselves are the mechanism to determine which tools is executabel on which bourreau. And here lies the problem: the Boutiques integration code create all the tool configs with group_id = 'everyone', which means that if the sysadmin doesn't double check everything, it allows users to start launching those docker tasks right away on any new bourreau that's added. That defeats the purpose of having control on who can launch what and where.

I think the tool configs should be created with group_id = 'admin' only, and then the sysadmin can change it back to something else, to make it available to who is suppose to run that toot.

**Comment by glatard** [comment]
setting the boutiques tool configs to `admin` only should be quite straightforward.

**Comment by prioux** [comment]
Done by #634
