### ISSUE TITLE
ToolConfig index table should provide links, also new columns

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#633]
- [x] Make execution server names links to their 'show' page.
- [x] Make the tool names link to their 'show' page.
- [x] Make the tool config names link to their 'show' page (just like the "Show" link already present on the right side of the table)
- [x] Add column with the group_id of the tool just after the tool name (and values linking to the groups)
- [x] Rename the column 'project access' to be 'Version Project", make entries be links to the groups
- [x] Add a column that links to the access report for that tool on that execution server

**Comment by cmacaulay** [comment]
@prioux I would like to take this on! Has it been claimed already?

**Comment by prioux** [comment]
Go ahead.

**Comment by prioux** [comment]
Fixed by #712
