### ISSUE TITLE
Swagger Validation Error

### ISSUE THREAD

**Issue by crocodoyle** [aces/cbrain#636]
The recent changes to the register/unregister userfiles in the Swagger specification have introduced an error. Before, they were of type String, and they were changed to accept Arrays but this was not updated everywhere it seems.

If you visit https://portal.cbrain.mcgill.ca/swagger, you can see the error message by clicking the Swagger validator icon in the bottom right corner of the page.

**Comment by crocodoyle** [comment]
Here's the error: 
```
{"messages":["attribute paths.'/data_providers/{id}/register'(post).[basenames[]].default is not of type `string`","attribute paths.'/groups/{id}'(put).[group[user_ids]].default is not of type `string`","attribute paths.'/data_providers/{id}/register'(post).[filetypes[]].default is not of type `string`","attribute paths.'/data_providers/{id}/delete'(post).[basenames[]].default is not of type `string`","attribute paths.'/data_providers/{id}/unregister'(post).[basenames[]].default is not of type `string`","attribute paths.'/groups'(post).[group[user_ids]].default is not of type `string`"]}
```

**Comment by shots47s** [comment]
crocodoyle, does your current pull request fix this issue?

**Comment by crocodoyle** [comment]
Yes in theory, but it is currently only tested in the Swagger Editor UI because on dev it doesn't run the validator by connecting to the Swagger main site.
