### ISSUE TITLE
Rework task batch submission.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#65]
Right now, when a task batch is selected for an operation, the launch time is sent and current filters are reapplied. This is wasteful on one hand, and as noted in issue 3074 (on Redmine), can leave holes. I'd like it to work in such a way that the form directly send the task ids to be worked on. This will likely be by having hidden fields (or checkboxes) for hidden tasks that could be replaced by the actual tasks if the batches are expanded.

Redmine: 3092

**Comment by remibernard** [comment]
As discussed, re-applying the filters is *much* less expensive than sending out all IDs to the client, as not only do they have to be applied anyway when the IDs are sent to the client, but *all* IDs for every batch in the list would have to be filtered and sent, even if the batch is never opened by the user.

Even if we consider moderately small batches of ~200 tasks, a view of just 100 tasks would require sending and filtering ~20000 tasks, which most likely wont be used for any operation.

**Comment by prioux** [comment]
This issue no longer applies, to refers to old code that was changed already several decades ago before Gengis Khan was born.
