### ISSUE TITLE
ToolConfig "show" page should provide more info about newest attributes

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#650]
We've added a lot of attribtues to the ToolConfig models, yet the "show" page only lists the `version_name`, `group`, and `ncpus` .
Let's maybe make it nicer and clearer; keep the full bash prologue well below the information.

We could have an option to show the info just for the TC, or the full set of inherited TCs (like it is now).

**Comment by MontrealSergiy** [comment]
also need more work on harmonisation with other pages (e.g. use show table)

**Comment by MontrealSergiy** [comment]
As discussed changed controller, routes, create new. Doing same to tool show/new

**Comment by MontrealSergiy** [comment]
sorry forgot to push one last corrections

**Comment by prioux** [comment]
Fixed by #765
