### ISSUE TITLE
ToolConfig project selection

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#663]
The project selection drop-down list in ToolConfigs is very difficult to navigate. For instance, it took me several minutes to find the PSOM project. It would be nice if a search box could be added.

![screenshot from 2017-11-15 09-29-32](https://user-images.githubusercontent.com/5174953/32841156-9f87e530-c9e7-11e7-92ba-fc2aad1e5d9f.png)

**Comment by prioux** [comment]
Fixed by #906
