### ISSUE TITLE
List available tools to everybody.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#664]
This page should be available to everybody (should be public).
We can use the API as a standard user to get the list of the available tools and set a regular task to update the list.

**Comment by prioux** [comment]
There is already a list of tools in the dashboard. It only shows the tools available to the user. We can update it so that it shows ALL the tools, while highlighting the tools that the user has access to.

**Comment by shots47s** [comment]
It may behove us to have this in a place that is external to the CBRAIN portal or doesn't require a user account to get to as that way we can make it useful in promoting what we have rather than just for people that have already drank the koolaid.

**Comment by prioux** [comment]
I think I'll add the list of tools to the login page, and I might as well add the list of userfile file formats...

**Comment by MontrealSergiy** [comment]
Is there possibility not to exclude some from that list?

**Comment by natacha-beck** [comment]
Closed by #1120
