### ISSUE TITLE
Clear the persistent selection list when switching project

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#671]
All persistently selected files should be cleared when the user switch project. Just to avoid problems. Users can still create list of files form multiple projects by working with no current project (the `all` project).

**Comment by prioux** [comment]
@shots47s @gkiar @crocodoyle @natacha-beck 

I have come up with a patch for this issue, but it's different from the proposed solution above.

Instead of clearing the persistent list, each project now has its own separate persistent list. This means if you are in project A with 3 selected files and you switch to project B, you'll see 0 selected files (assuming you've never selected any files in B before). If you switch back to A, you see your 3 selected files again. You can switch back and forth between any number of projects, and they will each have their own list.

Would this solution (which is basically a new feature) work for you, or do you guys think we really should CLEAR the persistent list no matter what? I can imaging it coudl still cause confusion if a user has 3 selected files in A, switches to B, see there are 3 selected files and assume they are the same (even though they can be 3 completely other files).

See also #685 for more discussion.

**Comment by prioux** [comment]
Just asking for your opinion.

**Comment by prioux** [comment]
Tagging @glatard too into the discussion.

**Comment by crocodoyle** [comment]
I think that this would be useful when working on several projects at the
same time and switching back and forth between them, but could cause even
more confusion if a user has set aside a project for a month or so, logs
back in and then still has files selected... It is much better than the
previous behaviour though. Maybe a consult with some users is in order on
this new feature

**Comment by prioux** [comment]
@crocodoyle thanks; I think I'm leaning more and more towards clearing the list too.

**Comment by prioux** [comment]
Interestingly it's way more difficult to clear the persistent list than to provide a distinct one for each project. The javascript support code for persistency is loaded only once in the userfiles index page during full page refreshes. Switching project can be done either from the projects index page or from an ajax request within the userfiles index.

**Comment by prioux** [comment]
I was wrong, switching project is always a full page refresh... that simplifies my life.

**Comment by prioux** [comment]
Well, not so much. :-(

**Comment by prioux** [comment]
@crocodoyle I just wasn't sure but as you can see I decided to flatly clear the list. Your comment provided the tipping point in my mind, thanks.

**Comment by natacha-beck** [comment]
Closed by https://github.com/aces/cbrain/pull/706
