### ISSUE TITLE
Boutiques tasks templates and class get overrriden if more than one descriptor has the same name.

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#672]
If two Boutiques descriptors contain the same tool name, the integration code in CBRAIN will load the first, create the task's class an its view templates, then when loading the second descriptor it will destroy all of that and replace them.

This happens for instance with the tool ndmg (https://github.com/neurodata/boutiques-tools) which has two descriptors, one for docker and one for singularity. Even through the task gets two distinct tool configs, the task's class itself undergoes the problem described above. If it happened that the two descriptors were containing different sets of input fields (or anything else unique in the interface), then in CBRAIN we would only get the input fields from whichever descriptor was loaded second.

**Comment by prioux** [comment]
We can tell this is happening by a boot message:

```
WARNING: Ndmg is already defined in CbrainTask; undefining to avoid collisions
```

**Comment by glatard** [comment]
We had long discussions on this topic with @remibernard. 
* if the descriptors also have the same version, I don't think we want to solve the issue. The fact that the same version of the same tool is implemented in different ways should be described as different tool versions, in this case ndmg-x.y.z-docker and ndmg-x.y.z-singularity.
* if the descriptors have different versions: From what I remember, CBRAIN doesn't support loading a specific class per tool version. Tool versions correspond to different tool configs but tool configs are invoked through the same class. In particular, all versions of the tool have to have the same portal-side class. This is a problem when different versions have different parameters, therefore different launch forms. We could workaround this be creating a new tool for each version, but that would completely circumvent CBRAIN's mechanism for tool versions. 

So I'm not sure how this is supposed to be solved in CBRAIN.

**Comment by prioux** [comment]
Yeah, I understand. My feeling is either:

1) When the integration of a task named Xyz is launched but there already was a task Xyz defined, assume it's simply the same task and skip the generation of all templates; silently proceed directly to the tool config creation (which can skip too if it already exists). This can lead to a situation where the form for both tool configs will lead to the same params layout and validation, which can be a problem if the two descriptors were suppose to describe different things. It's basically what's happening now, except it's the form of the second task that is used in CBRIAN, not the first.

2) reject the second task descriptor and refuse to boot, with a message: you have two descriptors for the same name, sorry. So the sysadmin has to contact the devs and ask for differentiation. This is the safest in the case the two descriptors DO define tasks with different params.

**Comment by glatard** [comment]
Either solutions work for me. Crashing a complete CBRAIN portal because of 1 plugin might be a bit radical, so 1. might be better.

**Comment by shots47s** [comment]
@prioux agrees 1) is the better solution.

**Comment by prioux** [comment]
Well, I'm closing the issue, leaving the current behavior intact. The plan was to slightly optimize the boot process by not having the templates instanciated every time, but the way the boutiques tasks are loading into cbrain makes that difficult and the effort is not worth it. The loading code is basically like

```ruby
   SchemaTaskGenerator.generate(schema, descriptor).integrate
```

where the templates are built and instanciated already in the `generate()` method, whereas the Tool and ToolConfigs objects are created in `integrate()`.

This means that within CBRAIN, we see the forms for the LAST descriptor loaded, period.
