### ISSUE TITLE
Easy way to access workdir.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#673]
When a task failed, is not easy to access the workdir in order to inspect the result: 

Accessing task work directories is possible but bulky: 
- needs to archive the task
- download
- then unarchive.

Should bring an easy way to do that.

**Comment by shots47s** [comment]
Need to find all of the other issues that pertain to this an link them here @shots47s

**Comment by natacha-beck** [comment]
This PR https://github.com/aces/cbrain/pull/721 allow saving the WorkDirectory as a TaskRawDirectory directly from the task pages. If it works with all of you (@shots47s , @prioux , @gkiar ) I will close this issue.

**Comment by prioux** [comment]
Done by Natacha in #721
