### ISSUE TITLE
Tasks page to refresh itself of to have a refresh button on the page

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#688]
For someone not familiar with the tool, it would easy to think nothing is happening, so we can put an autorefresh to the page or actually put a button that says "Update Status" on the page so that it is clear that something needs to be done to see the status change.

**Comment by prioux** [comment]
Fixed by #713, plus an additional commit:0399d6b1a89f8e86edbb9a527faa9ccf39529ce4 made on dev.
