### ISSUE TITLE
Task status indicating more than "New" when using a container

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#693]
Right now it appears that while a container is being pulled from a hub, the status of a Task stays at "New".  For large containers, this could take a long time and appears as if the task is doing nothing.  We could provide a status that indicates something more informative like "Preparing" or "Creating Container".

**Comment by prioux** [comment]
I don't think so... the task is supposed to be in state 'Setting Up', which is when the containers are being pulled... at least that's how I remember it...?

**Comment by shots47s** [comment]
'On CPU' is what is says on mine, sorry for the confusion, I will close the issue.
