### ISSUE TITLE
Add a category to the User model that tracks what level the user is.

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#709]
Many may have reporting requirements that entail reporting how many undergraduate, graduates, post dock etc... So I propose a simple dropdown select box in the user model that has the fields

1. Undergraduate Student
1. Master's Student
1. Doctoral Student
1. Post Doctoral Fellow
1. Professor
1. Research Staff
1. Other

**Comment by prioux** [comment]
You might want to create a data migration to populate the attribute based on hints stored elsewhere in the DB. E.g. 'Dr' in the full name, or the title entry in the user's log when the account was created by the signups subsystem.

**Comment by prioux** [comment]
Speaking of which, the signup subsystem should populate the attribute at account creation time.

**Comment by prioux** [comment]
Will be part of #887

**Comment by prioux** [comment]
Done by #887
