### ISSUE TITLE
GET /users returns funny error when called by session with NormalUser type 

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#732]
If you POST as session with a user that has a NormalUser, GET /users return the error

{
  "error": "Action 'change_password' not available to API. Available actions are [:index, :create, :show, :destroy, :update]"
}

**Comment by prioux** [comment]
It's not clear to me... you were POSTing to what path exactly? And then it's when you do a subsequent `GET /users` that you receive that message?

**Comment by shots47s** [comment]
POST /session to successfully create a session for a user that is of type NormalUser
GET /users produces the error
