### ISSUE TITLE
Cleanup: BrainPortal/views/tools/new.html.erb

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#737]
That file contains spurious code in large amounts (bottom part, table listing tools configs that can never exist).

**Comment by prioux** [comment]
For some reason the partial `form_fields` was removed too, and replaced as-is inside the file. Return to the partial so we can be DRY.

**Comment by Marijunjnja** [comment]
I would like to work on this issue

**Comment by prioux** [comment]
This was performed as pasrt of #809
