### ISSUE TITLE
Boutique integration issue on Bourreau side (renaming output race condition).

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#745]
On the Bourreau side integration of Boutique a task should rename the output with a unique id, if the same file is already present on the DP, it is a rare race condition but it can happen. We should always rename the task output with a unique identifier.

The code to modify, can be found here:

https://github.com/aces/cbrain/blob/57eb45c1a8f6de4b724c3be8cb0eb96ba149489c/BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb#L469

**Comment by prioux** [comment]
Yep, that's pretty bad, and likely to cause problems when thousands of tasks all finish a t teh same time with the same outpufile name...
