### ISSUE TITLE
Provide feedback to user on visualization when file is too large to visualize

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#760]
When a file is too large to visualize (i.e. exceeds 400mb, which I am not sure is actually a limit anymore given RAM on computers), the user is just presented either with a message that says it is unable to visualize a file type, or a reduced visualization with no information on what they should do next to view the file.  This should be changed to potentially provide them a link to information on how they can visualize it (i.e. a link to a visualization tool such as Brain Browser or a wiki page on how to download and visualize the file.

**Comment by prioux** [comment]
I'm going to go through each of the models in cbrain-plugins-base and add a viewer for the **opposite** conditions, with proper information.
