### ISSUE TITLE
Cannot create new tool

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#766]
TO REPRODUCE

1) go to the tool page
2) click new tool
3) fill all the fields with data
4) click submit

OBSERVED

Exception ( for some reason backend can't add licenses before object is created)

NOTES

that 'create xxx' pages no longer have licenses field, I guess licenses should be removed from new tool page as well.

**Comment by MontrealSergiy** [comment]
Katalan Script


click | link=Create New Tool |  
-- | -- | --
click | id=tool_name |  
click | id=tool_name |  
type | id=tool_name | CbrainTas:BashScriptor
click | id=tool_cbrain_task_class_name |  
type | id=tool_cbrain_task_class_name | CbrainTask::BashScriptor
click | id=tool_description |  
type | id=tool_description | CbrainTaskBashScriptor
click | id=tool_cbrain_task_class_name |  
type | id=tool_cbrain_task_class_name | CbrainTask::BashScriptor2
click | id=tool_description |  
click | id=tool_application_package_name |  
type | id=tool_application_package_name | bash
click | id=tool_application_type |  
type | id=tool_application_type | bash
click | id=tool_application_tags |  
type | id=tool_application_tags | bash
click | id=tool_url |  
type | id=tool_url | http://www.bash.org
click | id=tool_select_menu_text |  
type | id=tool_select_menu_text | bashscr
click | name=commit |

**Comment by prioux** [comment]
I think this is a bug that was introduced when making the license agreement module 'lazy': agreements strings are loaded from the meta data store only when the method is invoked.

We simply need to fix it so that license agreements CAN be set on an object that has't been saved yet.

**Comment by MontrealSergiy** [comment]
I see, it would be a better solution I guess

**Comment by prioux** [comment]
Yes, the changes go in this file here: https://github.com/aces/cbrain/blame/master/BrainPortal/lib/license_agreements.rb

**Comment by MontrealSergiy** [comment]
deleting a few lines allows Ruby to create objects with license_agreements . Not sure is there a reason for those lines  or were them just a precation.

**Comment by prioux** [comment]
I think removing the `raise` in `license_agreements=()` is correct, but your modification to `valid_license_agreements?()` is wrong. This is a ActiveRecord callback and you made it return true all the time without ever doing its validations.

**Comment by MontrealSergiy** [comment]
did you see the latest version?

**Comment by prioux** [comment]
Well, you reverted some changes but you still removed the `return true if self.new_record?` in the validate code, which I think is wrong.

**Comment by prioux** [comment]
Make sure that everything passes the test suite and if the test suite does not include a positive and negative test of the validation, add them please.

**Comment by MontrealSergiy** [comment]
I removed line specifically to allow test validation, but did not run unittests, tested manually with Katalon

**Comment by MontrealSergiy** [comment]
Added a few rspecs tests

**Comment by MontrealSergiy** [comment]
Note I did not find any traces of licenses on new servers and data providers pages so I did not try to add any licenses there.

**Comment by prioux** [comment]
Fixed by #776
