### ISSUE TITLE
Boutiques/CBRAIN and Singularity/Docker integration.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#774]
If a Boutiques descriptor specifies a `container-image` of type `docker`, CBRAIN will not configure a new ToolConfig on a cluster that does not have a `docker` engine defined. 

The process to convert a Docker container as a Singularity container is stable enough to set up a ToolConfig for this task and to define the Container engine as `Singularity` if Singularity is present on the cluster. 

By doing that CBRAIN will be able to create and used Singularity image by building them from a docker reference.

**Comment by gkiar** [comment]
(crosslist with boutiques/boutiques#298)

**Comment by prioux** [comment]
Isn't this already implemented, @natacha-beck ?

**Comment by prioux** [comment]
Oh, no, the issue is about the tool config automatically created by the integrator. Never mind my previous comment.

**Comment by prioux** [comment]
Implemented in #1170
