### ISSUE TITLE
List parameters are dissapering during the edit (bug)

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#784]
**To reproduce**
1. Install BEst boutiques (probably any tool with a list parameter would trigger the same bug)
2. Create a task
3. Run the task 
4. Wait for termination (or break)
5. Find the task, click edit parameters button
6. Click some fields, change a few parameters
7. Launch the task 

**Expected** Task executes successfully

**Observed** Error message, because an element of the list dropped

**Comment by prioux** [comment]
Can you try with the Diagnostics task to make sure it's not a framework bug?

**Comment by prioux** [comment]
Also, what do you see in the task's log after step 6? All changes to parameters are supposed to be logged by the task submission framework. Do the logs make sense?

**Comment by MontrealSergiy** [comment]
Not much logs, I guess need to remove array length validation to get some

**Comment by prioux** [comment]
It think the bug is at line 149 here:

https://github.com/aces/cbrain/blob/master/BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb#L149

It should be like line 138 above (missing the `+ []` for the name of the parameter)

**Comment by prioux** [comment]
Fixed directly on master in https://github.com/aces/cbrain/commit/1f40c17d18d17a82b3416b853df26ef1cb6cd87f
