### ISSUE TITLE
API not-found error code

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#785]
If we follow usual HTTP conventions, API should return error code 404 for nonexisting items (page/resource not found), and not 500 (server error). Use case: correct return code helps API user, that is front-end developer, generate a correct error message, or diagnose an issue in his own code (e.g. mixing  tools vs bourreaux or file ids), 

**To reproduce**
1) generate a random number 
2) procure an api tocken say 3333333333
3) send an http request (using curl, postman or whatever your prefered client)  `localhost:3000/bourreaux/random_number?token`
 where token is authorization token and randon_number where obtained in previous steps

**Observed**
HTTP status  code 500

**Expected**
HTTP status code 404

Using correct codes helps API to diagnose problem.

**Comment by prioux** [comment]
I get a proper 404 error code. I think maybe your test environment isn't set up properly? Trying to find a record that doesn't exist raise a ruby `ActiveRecord::RecordNotFound`, which triggers the exception handler 'record_not_found' in lib/exception_helpers.rb  ; that in turn returns the 404 code properly.

That being said I got some HTML output in the body, even when requesting application/json, so that needs to be fixed.

**Comment by MontrealSergiy** [comment]
Yup on production I see correct 404 code ( on my PC Rack error <ActiveRecord::RecordNotFound>)

**Comment by MontrealSergiy** [comment]
I see no HTML in response, just a fine JSON message do you see an issue with it?

**Comment by MontrealSergiy** [comment]
(Actually not so fine) but still meaningfull

{
    "error": "Couldn't find RemoteResource with 'id'={{id}}"
}

**Comment by prioux** [comment]
Side note: I think in `exception_helper.rb` we could consider changing all lines such as:

```ruby
raise unless Rails.env == 'production' #Want to see stack trace in dev.
```

to

```ruby
raise if Rails.env == 'development' # Want to see stack trace in dev.
```

Not sure of the consequences, though.

**Comment by MontrealSergiy** [comment]
https://portal.cbrain.mcgill.ca:4000/bourreaux/33333

also giving 404

**Comment by prioux** [comment]
I just tested again, and all seems fine:

* In development environment, we get 404 with a HTML page with stack traces etc, which is expected
* In a production environment, we also get 404 with a JSON error message

I wasn't able to get a 500 ever.
