### ISSUE TITLE
Cookie affects the API (it should not)

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#786]
According to Swagger CBRAIN API should rely on authentification token, not cookies. 
Yet presently POST session/?user=...?pwd returns token according to the cookie if any rather than the token.

I observed the error with Postman API testing tool, which stores the cookies for more realistic testing.
Probably the same can be observed using any browser-based API testing tool  and other API endpoints.

The issue might confuse users who use several logins for different projects (e.g. depending on affiliations) or share same PC.

**Comment by prioux** [comment]
I don't understand what is to fix here... if a program has a token, CBRAIN will use it to verify authentication. If cookies are exchanged, that becomes a fallback (what browsers do). Does the API in the cbrain-client gem ceased to work? Do browsers cease to work? Can you please give me an exact reproducible example of a problem?

**Comment by prioux** [comment]
@MontrealSergiy Please explain precisely and give me an example, like I asked.

**Comment by MontrealSergiy** [comment]
Generally speaking, REST API's are supposed to be 'stateless' https://restfulapi.net/statelessness/ .

meanwhile I am trying to make up more clear scenario soon.

**Comment by prioux** [comment]
I know what REST is and the CBRAIN API has never had a requirement to be totally restful. In fact we don't want it to be.

**Comment by MontrealSergiy** [comment]
Ok, if it is on purpose I do not mind cancelling the ticket.

Looks like there are a few big name api's with cookies support.

If you have time I can show you some thing from my desktop
but I do not have a good reproducible scenario so far.

**Comment by MontrealSergiy** [comment]
Do you think two different 3-rd party apps can use cbrain api on same browser with no issues?

**Comment by prioux** [comment]
Probably not, but one way to be sure is to disable sending back the cookie whenever we are working with API requests. It should be pretty simple.

**Comment by prioux** [comment]
I wrote the code by before committing it I wanted to check how oftne API requests generate cookies. Adding the "-c" option to curl revealed that NONE of the API request generate a cookie! The only exception was when testing the specific `users/badnormpatch` test, and I'm not sure why either.

**Comment by MontrealSergiy** [comment]
For me /session?login=username&password=wrongpassword generates a cookie even if password is wrong

**Comment by prioux** [comment]
Actually I'm getting a cookie for all PATCH and POST and PUT

**Comment by prioux** [comment]
I made a commit, if TRAVIS CI is satisfied I'll create a PR.

https://github.com/prioux/cbrain/commit/b166f611854fdfffdc1f9e0d44ce0b13893b8df8

**Comment by MontrealSergiy** [comment]
... who is using api? Xavier? give him head ups?

**Comment by prioux** [comment]
Fixed by #888
