### ISSUE TITLE
Add the ability to set the batch for a large set of tasks through the API

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#790]
Currently, and it is very likely, if one launches a very large number of tasks through the API, there is no way to batch the tasks, which makes it very difficult to manage a set of runs through the UI.  We should provide the ability to set the batch_id somehow and have it stick so that when someone is managing their runs, they can take advantage of this nice feature.

**Comment by prioux** [comment]
Steps: when receiving an explicit batch_id, make sure it is the id of another task that the user has access to. If not, set it to nil. The rest of the code will work fine as-is, because the main loop for saving objects use `task.batch_id ||= task.id`

**Comment by prioux** [comment]
Fixed by #810
