### ISSUE TITLE
Verify that switch_panel and inline_edit_form is useless.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#81]
During the #:nodoc: session, we have seen that:

- the switch_panel method.
- the inline_edit_form method.

Seems to be useless, need to be double check and removed if necessary.

**Comment by remibernard** [comment]
The switch_panel functionality was removed as part of what seems to be a refactor of the interface, see commit a526deac2cae7440b9767583b5c22ee3250a9a3d. There is no reference to the partial or method anywhere else.

**Comment by remibernard** [comment]
Searching through the commit history for inline_edit_form reveals the method never had any callers and is part of the inline_edit_* JS-based rich edition functionality. It was introduced in commit d9df96177b161c49520d
