### ISSUE TITLE
DP consistency checker interface improvements

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#819]
The DP consistency checker could benefit from some improvements:

1) direct links to it from the DP index page
2) not to show files that are unregistered as this is not much of a problem really (but maybe keep it as an option?)
3) when triggering the 'repair' process, spawn it in background instead of blocking the rails request
4) better categories for the different possible errors
5) filtering of the report table

**Comment by natacha-beck** [comment]
Some of this issues are the same mentioned here: #593

**Comment by prioux** [comment]
Fixed by #918
