### ISSUE TITLE
File lists and Boutiques-based tools

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#831]
**Intro**: 
CBRAIN supports import of tools in Boutiques format. Regretfully, input parameters of FIle type in Boutiques tool descriptors, are not properly supported in CBRAIN, while, I think users and tool developers could benefit from full file list support.

An example of the file list input in Boutiques format:
```
        {
            "id": "list",
            "value-key": "[list]",
            "list": true,
            "command-line-flag": "--list",
            "description": "Some file list. Could be e.g. the list of files with MRI data to analyze.",
            "type": "File",
            "name": "files (with MRI data_"
        },
```
(see https://raw.githubusercontent.com/MontrealSergiy/cbrain-plugins-eeg/bugs/cbrain_task_descriptors/filelistbug.json for full descriptor)
CBRAIN seemingly imports boutiques descriptors with file lists without any warning or error message, configuring and executing tool's task is ridden with several issues.

**Steps to reproduce issues**:
1. Create boutiques with a file list input, download from above GitHub link, ( or copy one from Boutiques tests).
2. Import boutiques into CBRAIN;
3. Create a task and a) try to populate the input with more than one file b) run it (with one file list).

**Observed**: User can only supply one file per input, and, anyway, the command line will be malformed and (usually) fail

**Expected**: User should be able to provide multiple files and put them into file list, perhaps in the same way he can create integer or string lists

**Note 1**: The lists of numbers or strings are supported by CBRAIN, the problem is with file lists

**Note 2**: Older versions of boutiques had a few issues with file lists, which are fixed by now

**Comment by prioux** [comment]
Implemented in #832
