### ISSUE TITLE
Establish a code of conduct for CBRAIN project

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#835]
Would be nice for us to have an actual code of conduct for our project.  Here is an example I found that we could tailor to our project.  

http://citizencodeofconduct.org/

Let me know what you think?

**Comment by prioux** [comment]
Good idea.

Some sections will need to be removed, and maybe just replaced by a paragraph that says that all of McGill University's own rules apply and in case of conflict overrule anything else we write in our code of conduct.

I also suggest that maybe we should make requirement that no contribution can be anonymous, only code from identified human beings will be integrated into cbrain. Just an idea, what do you think?

**Comment by prioux** [comment]
Rule number 6: there is no rule number 6.

**Comment by glatard** [comment]
Hi, I have always relied on [Contributor Covenant](https://www.contributor-covenant.org/). The only required edit is the email address to use in case of problems. This is what CONP use now, see example here: https://github.com/CONP-PCNO/conp-portal/blob/master/.github/CODE_OF_CONDUCT.md

I'm not sure about mentioning McGill's rules here: if the goal is to regulate conduct of open source contributors, many of them won't be McGill employees and wouldn't even know about these rules.

**Comment by shots47s** [comment]
So I won't be able to harass people anymore?

**Comment by prioux** [comment]
@shots47s Only the people who report directly to you.

**Comment by shots47s** [comment]
Whew, actually this looks like a good start @glatard, how about I edit this up and put in a pull request? Any objections?

**Comment by glatard** [comment]
no objection on my side of course :)

**Comment by shots47s** [comment]
The CONP one is in the .github directory, is that a necessity or can I just put it in the top directory where the license is?

**Comment by glatard** [comment]
You should put it in the .github directory so that it shows in the community list: https://github.com/aces/cbrain/community

**Comment by prioux** [comment]
We already created a security policy in our .github for the ACElab, but we rejected creating a code of conduct for all projects, because each projects might have distinct requirements. E.g. projects that do not allow IPA drinkers, etc.

**Comment by shots47s** [comment]
Discussion moved to PR: #836, will close this discussion and we can finalize there.
