### ISSUE TITLE
Repeated config links on a tool's page

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#854]

**Comment by MontrealSergiy** [comment]
Presently, on a tool page, a row representing a config has [more] link and show link. I think we do not need too, maybe just kept show? Or put a link on the version name instead?

![image](https://user-images.githubusercontent.com/11949081/63057131-83245600-beb7-11e9-830c-64ae3751c0a7.png)

**Comment by natacha-beck** [comment]
It is not a repeated link.

The `more` allows having an overlay with the description of the tool. 
And the `show` one point to the show page of the `tool_config`

**Comment by MontrealSergiy** [comment]
Ah, ok, got it. May be not 100% clear UX but serves a purpose
