### ISSUE TITLE
Publish to Zenodo button for exporting the full task to Zenodo for provenance capture

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#855]
Thought I had created this, but did not.

Feature would be to give the user the ability for a completed Boutiques task to publish enough information to Zenodo to reproduce the result of the pipeline in CBRAIN (and potentially other platforms).

Current list of things that need to be published would be at minimum:

1) The Singularity Image the pipeline used to run.
2) The Boutique descriptor that was used to define the pipeline.
3) The input parameters or invocation for the pipeline.
4) The input data (potentially sensitive, so need to make optional, at least then some representation so that we can get it back from CBRAIN if needed).
5) The output data (potentially sensitive, so need to make optional, at least then some representation so that we can get it back from CBRAIN if needed).
6) A JSON capturing the information that is related to the execution that may cause the singularity image to have an altered execution on different computational hardware (tricky).

There would be a button that automates this and provides the user a new interface component to control the process including the option to publish to Zenodo as "Closed", "Open", "Registered", or "Embargoed".  

Each component should be uploaded separately and uniquely identified with a DOI.

Conversely, we could provide an import from Zenodo button that gives the user the ability to re-import the information into CBRAIN. 

All of this should have a "caching" mentality, i.e. if the data is already where it needs to go (i.e. the Singularity image is already in Zenodo), then the existing data is used.

**Comment by MontrealSergiy** [comment]
I guess for now button goes on task (or task list).

I guess ideally the cache of singularity image should be controlled by cache sum or smth.
Also caching leaves possibility one user decision to unpubish task  deleteing tool image shared by several tasks.

**Comment by shots47s** [comment]
For Zenodo API Key, we make these a part of the user profile.

**Comment by glatard** [comment]
It would be great if points 2, 3, and perhaps 5 could be compatible with what is tracked and published by `bosh data`. The PR in https://github.com/boutiques/boutiques/pull/532/files adds the possibility to append an arbitrary object to it.

**Comment by prioux** [comment]
Any idea how we can handle gracefully entire large task arrays? E.g. civet over 1000 subjects, or a bids app with a bids dataset with 1000 subject? Each individual task contain only the params for that task (and doesn’t know it is part of a larger whole). Also, possibly, individual task might have been reatarted with slightly different params (eg because of a failure with the standard params), so we can’t assume all of them have identical params.

We also don’t want to upload the same input dataset 1000 times.

And then there is the problem of a group stage (eg CivetQC). Its input is the regrouped outputs of all the individual subject tasks. We don’t want duplications either...

**Comment by shots47s** [comment]
@glatard 2 and 3, easy, 5 I guess we have to figure out first how to publish outputs sanely.

**Comment by shots47s** [comment]
@prioux, as I see it, we have two options....

1) upload everything as a monolithic entity... i.e. place all of the inputs and all of the outputs as one zenodo entry

So in your example, gather it all together, upload a zip of it and only do that once.  For BIDS apps, this makes some sense as they are "dataset". For the 1000 civet runs on a collection of image files, may not be so easy.  Although, there is no reason we must treat these the same, we could make a bids app behave differently.

2) break it apart into pieces, upload each individual piece and then somehow string them together as a network of items.

This is easy for the CIVET case (although the stringing them together will take some work, but it pulls apart a bids like dataset into constituents, which may be challenging.  

The only bottleneck we have is the 50 GB limit on a single Zenodo entry.  Do others have thoughts about this?

**Comment by prioux** [comment]
50GB won't allow us to upload any BIDS datasets except toy examples...

I also would like to avoid uploading the same data many times. When we provide datasets in CBRAIN, a user can run tasks on it, and another user can run other tasks on it (or the same with different params), and so when saving to zenodo we don't want several copies.

I'm thinking that maybe whenever we upload a piece of data to zenodo, we record in CBRAIN the zenodo ID within the userfile record. So after the first time something is uploaded, the ID can be re-used later on.

**Comment by prioux** [comment]
However, the IDs are tied to specific user accounts, so we have to be careful: we want the public datasets in CBRAIN NOT to be uploaded and be tied to the first cbrain user that use it.

**Comment by prioux** [comment]
This issue has WAY too many unresolved problems, until we have a precise spec, I think we should put it on ice.

**Comment by MontrealSergiy** [comment]
1. For a prototype (only visible to a certain group, or may be even admin) do not handle over 50G things. <50 put in same archive/folder. 

2. For final version: elaborate way to split task in <50G e.g. using abovementioned 'caching' mentality. a) may crump missing part info into metadata file? or b)Is it possible to copycat or recycle any existing solution, like git annex?

**Comment by shots47s** [comment]
@prioux the purpose of this issue is to flash it out, so let's continue to do so until there is consensus on a plan.

**Comment by shots47s** [comment]
How about we simplify the problem in the first pass. Let's narrow this down to publishing the results of one task with one datasets. So say a CIVET or FreeSurfer run on one particular image, just to simplify what we are trying to do at first.  @prioux does this narrow it down a bit for you.

**Comment by prioux** [comment]
Quick personal notes:

1) add script in Bourreau/vendor/cbrain to capture run-time node info; exec at same place as 'times'
2) add .to_zenodo() method to PortalTask model; returns `{ :inputs => [ u1, u2 ], :outputs => [ u3, u4 ], :xyz => :abc }`
3) interface show page for task checks method_defined and zenod account for user, shows button

**Comment by prioux** [comment]
Capture accounting when post-processing starts: (slurm only)

```
sacct -j 17703997 --delimiter=, -P --format=Jobname,state,elapsed,MaxRss,MaxVMSize,nnodes,ncpus
JobName,State,Elapsed,MaxRSS,MaxVMSize,NNodes,NCPUS
Civet-903002,COMPLETED,07:25:37,,,1,1
batch,COMPLETED,07:25:37,860425K,1772540K,1,1
extern,COMPLETED,07:25:37,676K,173996K,1,1
```

Todo: log this in new database resource usage table, linked to job ID too

CC clusters store the info for 6 months

**Comment by prioux** [comment]
We can also get the CPU:

```
gra-login1 ~ > sacct -j 17703997 --format=Jobname,state,elapsed,MaxRss,MaxVMSize,nnodes,ncpus,systemcpu,usercpu
   JobName      State    Elapsed     MaxRSS  MaxVMSize   NNodes      NCPUS  SystemCPU    UserCPU 
---------- ---------- ---------- ---------- ---------- -------- ---------- ---------- ---------- 
Civet-903+  COMPLETED   07:25:37                              1          1  04:22.504   07:14:56 
     batch  COMPLETED   07:25:37    860425K   1772540K        1          1  04:22.502   07:14:56 
    extern  COMPLETED   07:25:37       676K    173996K        1          1  00:00.002   00:00:00 
```

**Comment by prioux** [comment]
bosh publish data info example:

```json
{
    "summary": {
        "name": "fsl_bet",
        "descriptor-doi": "10.5281/zenodo.1482743",
        "date-time": "2019-06-09T02:22:20.677452"
    },
    "public-invocation": {
        "infile": {
            "file-name": "test.nii.gz",
            "md5sum": "9daa5cff15e633a044b0df44a626abe1"
        },
        "maskfile": "test_brain.nii.gz"
    },
    "public-output": {
        "stdout": "",
        "stderr": "",
        "exit-code": 0,
        "error-message": "",
        "shell-command": "bet ./data/test.nii.gz test_brain.nii.gz                   ",
        "missing-files": {},
        "output-files": {}
    }
}
```

**Comment by prioux** [comment]
The PR has been merged; we'll open new issues when we need to implement new features or make other adjustments.
