### ISSUE TITLE
Adjust type selection box when creating new Data Providers

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#86]
The entries in the box should be sorted; LocalDataProvider should not
be available (it's an abstract class).

Pierre

**Comment by eafkhami** [comment]
My fix is below:

def get_type_list #:nodoc:
    # This list may contain 'LocalDataProvider' which is useless in any environments
    # where there are distributed resources. It would only work in a CBRAIN environment
    # where all portals and bourreaux are on the same machine.
    
    # The above comment is not entirely accurate. Somethin about file systems being shared between two machines.
    # Ask Tristan
    
    # to remove 'LocalDataProvider', we're adding conditional statement so if either of the two
    # situations mentioned above arise, we can show the correct types. For now we remove 'LocalDataProvider' 
    
    if true
      (check_role(:site_manager) || check_role(:admin_user)) ? DataProvider.descendants.map(&:name).delete_if{|elem| elem == "LocalDataProvider" }.sort_by{|elem| elem.downcase} : %w{ SshDataProvider }
    else 
      # this is the condition where all portals and bourreaux are on the same machine. check for this.
      # It was suggested to ask the user if all portal and bourreaux are on the same machine and check that condition
      (check_role(:site_manager) || check_role(:admin_user)) ? DataProvider.descendants.map(&:name) : %w{ SshDataProvider }     
    end
    
    
    
  end

**Comment by prioux** [comment]
Suggested option groups:

= Enhanced CBRAIN Types
* EnCbrainLocalDataProvider
* EnCbrainSmartDataProvider
* EnCbrainSshDataProvider

= Incoming Vault Types
* IncomingVaultLocalDataProvider
* IncomingVaultSmartDataProvider
* IncomingVaultSshDataProvider

= Vault Types
* VaultLocalDataProvider
* VaultSmartDataProvider
* VaultSshDataProvider

= Single Level Types
* SshDataProvider

= Other Types
LorisAssemblyNativeSshDataProvider
S3DataProvider

**Comment by prioux** [comment]
After discussion:

* Add new class method to subclasses of DataProvider: e.g.

```ruby
def self.pretty_category_name
  "Enhanced CBRAIN Storage"
end
```
Use those strings to regroup the types in the selection box.

Classes that return NIL are not to be included in the selection box (e.g. DataProvider or LocalDataProvider).

**Comment by eafkhami** [comment]
I've added the above changes and pushed to master
