### ISSUE TITLE
Userfile 'show' page to detect when data marked as 'Corrupted'

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#87]
The userfile 'show' page has a long list of if/else statements to make sure
that the file's content is ready to be diplayed; add another case, where if
the file's content on the Data Provider is marked as 'Corrupted' a nice error
message is shown to the user:

     The content of this file seems to be corrupted. This might be the result of a bad data transfer while it was being created or a filesystem failure. There isn't much you can do about this, although if the file was produced by a task, consider restarting the task's Post Processing stage.

Maybe in nice 'error' pink.

**Comment by eafkhami** [comment]
added the condition

**Comment by eafkhami** [comment]
There was a bug with adding this condition. When the sync_status didn't exist. This will be fixed in my next pull request.
