### ISSUE TITLE
Adjust beginning-of-day and end-of day when DateTime parsing for filters

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#892]
We have a date filtering panel helper that allows a user to select a range of dates from a calendar. The dates are returned to the Rails app in format such as `06/11/2019` . Right now, when given such a date, the time component is set to "00:00:00" (basically midnight). Which means that if a user selects, say, a range from the 3rd to the 4th of the month, the filtering will occur between midnight on the third to midnight on the fourth, giving a range of one day instead of two.

Adjust the parsing so that the start date stays at midnight but the END date ends at 23:59:59.

**Comment by natacha-beck** [comment]
@prioux should already be ok: 
https://github.com/aces/cbrain/blob/master/BrainPortal/lib/date_range_restriction.rb#L92

**Comment by prioux** [comment]
Yep. Excellent.
