### ISSUE TITLE
ResourceUsage data filtering seem to ignore the "To" date

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#937]
For the resource usage index page, we have the capability to filter by date ranges; it seems the "to" date is ignored.

**Comment by MontrealSergiy** [comment]
It works for me if I enable 'additional filtering' radio box. But, for more intuitive UX maybe verbiage can be changed? Or gray out the second field based on the first radio box?

**Comment by MontrealSergiy** [comment]
![image](https://user-images.githubusercontent.com/11949081/82339591-34fb3080-99bc-11ea-9c1a-3a3bdad43ae7.png)

**Comment by MontrealSergiy** [comment]
![image](https://user-images.githubusercontent.com/11949081/82341975-164a6900-99bf-11ea-9b13-a5bc9769407b.png)
added a snapshot of the filter for clarity/reproducibility
