### ISSUE TITLE
 Link method link_to_site_if_accessible() always produces a clickable link even for site that are not accessibles for the current user.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#94]
That is because site.rb doesn't have a can_be_accessed_by?() method, because that model doesn't include the module ResourceAcess (should it?).

Solution: if ResourceAccess is compatible, include it. If not, include a custom version of can_be_accessed_by?().

Pierre

**Comment by eafkhami** [comment]
This was fixed. The changes are in my master
