### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - license and green buttons

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#952]
Reference survey containing raw data feedback in spreadsheet format:
https://docs.google.com/spreadsheets/d/1yt3iKKlMoRUgZl9E_fomAVgj38CgvJ2K3AKIeB3tMDQ/edit#gid=675520657

Feedback from Jérôme Dockès regarding the following technical experience issues (to split as needed into separate items):

- after entering a license, on the page where I check a box to sign it, there is no text on the two green buttons at the bottom right of the page. I didn't realize I was supposed to click one of them at first. (using Mozilla Firefox 76.0.1)

**Comment by MontrealSergiy** [comment]
1. I see only one green button and clearly read texts with Mozilla 77.0.1 (win 10) . Should I downgrade to 76 to reproduce?

2. Even though I suspect the issues was on testers PC I guess give more clear instructions:
after 
CAREFULLY READ THIS LICENSE AGREEMENT. -> 

add
 to access project you have to sign now the license agreement(s). If you agree with term of this agreement please check the checkbox at the bottom and submit form by click the green "I agree ... " button at the bottom of this form.

**Comment by MontrealSergiy** [comment]
![snapshot_greenbutton](https://user-images.githubusercontent.com/11949081/86045814-1e63e280-ba1a-11ea-95c8-09ca9c825315.png)

**Comment by MontrealSergiy** [comment]
Sometimes atrocious, buggy or malicious browser extensions cause rendering issues. Could we ask tester to reproduce the issue in the private mode? (He or she should  use menu or press Ctrl+Shift+P to open a private window)

**Comment by bryancaron** [comment]
Serge, please ask user to retry with the incognito mode and see.

**Comment by MontrealSergiy** [comment]
user is asked to retry incognito

**Comment by MontrealSergiy** [comment]
Tester replied

> Hello Serge, sorry for the late answer.
> I have tried to reproduce the problem today and I could not reproduce
> it, neither with a regular or private window.
> I have updated firefox since last time and am now using Firefox 78.0.2
> My OS is ubuntu 18.04.
> 
> Good luck with this beautiful project!

**Comment by prioux** [comment]
Nothing else to do here.
