### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - collaborator email mismatch and notification

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#953]
Reference survey containing raw data feedback in spreadsheet format:
https://docs.google.com/spreadsheets/d/1yt3iKKlMoRUgZl9E_fomAVgj38CgvJ2K3AKIeB3tMDQ/edit#gid=675520657

Feedback from Jérôme Dockès regarding the following technical experience issues (to split as needed into separate items):

- when inviting collaborators, If I enter one email address of a registered user and one that doesn't match a user (separated by spaces), the message says "successfully sent" and doesn't tell me that the invitation failed for one user.

**Comment by MontrealSergiy** [comment]
@prioux should I fix this, unless there is a security issue?

**Comment by MontrealSergiy** [comment]
I think adding `No user was found with email(s) {wrong_emails}, we are not able to invite them. At the moment only invitation of already boarded users is supported. Please ask them first to join NeuroHub, or if you expect a typo in the email address, ask them with which exactly email they are registered to NeuroHub. `
