### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - single file upload limit

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#954]
Reference survey containing raw data feedback in spreadsheet format:
https://docs.google.com/spreadsheets/d/1yt3iKKlMoRUgZl9E_fomAVgj38CgvJ2K3AKIeB3tMDQ/edit#gid=675520657

Feedback from Seun Jeon regarding the following technical experience issues (to split as needed into separate items):

- Only one file at a time can be up/downloaded to/from the web.

**Comment by natacha-beck** [comment]
As discussed it is a limitation of CBRAIN in order to not overload the server.  

We can add a link to existing documentation about how to use CBRAIN SFTP Dataprovider, here: 

https://portal.cbrain.mcgill.ca/doc/manual/CBRAINGettingStartedGuideFeb15.pdf

**Comment by bryancaron** [comment]
Can we please check to see if this limit is visible to users in NeuroHub?

**Comment by natacha-beck** [comment]
@bryancaron the limit is not visible to NH user: 
+ Miss some JS code on NH side. 
+ Miss link to CBRAIN support documentation. 

Less easy than I think, totally doable. But it miss more part than just adding a link 

I take this one.

**Comment by natacha-beck** [comment]
Done by #983

**Comment by prioux** [comment]
Closed by #983
