### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - collaborator invitee search

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#955]
Reference survey containing raw data feedback in spreadsheet format:
https://docs.google.com/spreadsheets/d/1yt3iKKlMoRUgZl9E_fomAVgj38CgvJ2K3AKIeB3tMDQ/edit#gid=675520657

Feedback from Seun Jeon regarding the following technical experience issues (to split as needed into separate items):

- The host user must know the exact "cbrain account email" of the invitee.

**Comment by MontrealSergiy** [comment]
@bryancaron I think we implemented exact email for security purposes. So hackers cannot find out which users / or and emails are in cbrain easily @prioux  . Well they can go try and error for all random emails. but that can be amended one day with putting a quota on invites. Not sure should we relax secuirty/privacy

**Comment by natacha-beck** [comment]
Agree. 

I am ok to tell people that the email they put on the invitation list is not a good one (if he makes a typo). 
But not agree with a search function for me it is a privacy issue. It was discuss at NH meeting.

**Comment by prioux** [comment]
I'm thinking we could also support people adding other people using their usernames? The only prob with that is sometimes we have people with usernames that are really similar (e.g. `jwu` vs `jswu` vs `ejwu` (I made these up here, but just to show what can happen if a user is differentiated from another user by a middle name initial).

**Comment by MontrealSergiy** [comment]
Well that would address the problem user complains. Even fuzzy search can be implemented say with appropriate gem (may be just in search bar).  Also I think if, as planned we add project join request the issue would be alleviated. The join request feature specs though might not easy to design

**Comment by bryancaron** [comment]
As we discussed, we can support either the username or the registered email of the user.

**Comment by MontrealSergiy** [comment]
no problem will add username.

**Comment by MontrealSergiy** [comment]
@prioux I can take it if you like
