### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue -  login sequence issue between NeuroHub and CBRAIN

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#956]
Reference survey containing raw data feedback in spreadsheet format:
https://docs.google.com/spreadsheets/d/1yt3iKKlMoRUgZl9E_fomAVgj38CgvJ2K3AKIeB3tMDQ/edit#gid=675520657

Feedback from Lex Hutton regarding the following technical experience issues (to split as needed into separate items):

- Logging into NH redirected me to CBRAIN instead of NH. 
- Re-logging brought up an error ("a message was sent to admins").
- Further logins sent me to NH.

**Comment by bryancaron** [comment]
Is this reproducible?
Can use a flag to keep track if the connection was through NeuroHub or CBRAIN.
Can also help for navigation.

**Comment by natacha-beck** [comment]
I think this is link to #957

**Comment by prioux** [comment]
Problems described in details in #991
