### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - user registration, login and UI flow 

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#957]
Received via direct email message sent to Diana:

a) I tried to log-in with my Orcid ID
I was correctly re-directed in Orcid environment – I typed my credentials then I got this message
"No NeuroHub user matches your ORCID ID. Create a NeuroHub account, or add your ORCID ID to your account."
 
I was not sure what to do, I did not see any ‘ADD your ORCID ID to your account’ so I decided to create a NeuroHub account.
Note: The ‘request an account’ option should be in the log-in section

b)In the form to request an account, I was wondering what kind of ‘nickname’ should I use, just my name, something funny, or more professional? I was not clear if you recommend to have only one letter + numbers or if it was meaning that its mandatory to have at least one letter. It is necessary to have that ‘preferred login name’ ?

PREFERRED 'LOGIN' NAME
(one letter + alphanums)
 
c) For current position, I would harmonize
PhD Candidate
Master degree Candidate
Undergraduate student
And I would add:
Research professional
Health professional
Physician

d) After requesting an account; it took about 1:30 h to get the email to verify the email address… and I received it twice.
Once I got the ‘welcome to CBRAIN’ email, it felt weird, as a user, to be re-directed to CBRAIN.. and ‘access CBRAIN’… terms of use of CBRAIN…. etc, even if it’s says powered by CBRAIN at the bottom. I think this will need to be changed for NeuroHub…?!

e) I followed the steps and I was naturally connecting and navigating in CBRAIN. I had to close the window and go back to Neurohub platform and log-in with the credentials freshly obtained through CBRAIN. It felt wrong.
NeuroHub use my CBRAIN username (automatically given) instead of the ‘preferred login name’ mentioned in my ‘NeuroHub request form’

**Comment by prioux** [comment]
Yep we need to document for users:
1- user gets neurohub account
2- user connects with login password
3- user ADDs ORICID ID
4- at that point user can, in the future, login in with orcid

**Comment by prioux** [comment]
for b) we the login name is a suggestion but we ignore it if it's too unlike our conventions

**Comment by prioux** [comment]
For c) that list of titles was agreed upon last year with Shawn

**Comment by prioux** [comment]
for d) email are sent immediately ; the welcome email is created by CBRAIN, we can create a template for neurohub with a neurohub specific text

**Comment by bryancaron** [comment]
Skip c).  Nothing to change.
d) already addressed, to be confirmed.

**Comment by prioux** [comment]
for e) I suspect it's the forced password reset that trigger this back and forth.

**Comment by natacha-beck** [comment]
Need double check the content of the message on the email

**Comment by bryancaron** [comment]
d) to double check the content of the email notification message.

**Comment by bryancaron** [comment]
for e) need to enforce password reset for neurohub first logins.

**Comment by prioux** [comment]
For e) inplement password reset page in neurohub, triggerd when account is marked as need a password reset

**Comment by bryancaron** [comment]
For b) re: username we should give a brief outline of our convention when prompting the user for their preferred username.

**Comment by natacha-beck** [comment]
#972  adress point `b` and `d` by https://github.com/aces/cbrain/pull/972. 

Still need to look at `a` and `d`

**Comment by natacha-beck** [comment]
Now I better understand point `d`.
When an admin creates an account CBRAIN will send an email to the user newly created, saying: 

> Welcome to CBRAIN! 

We will be able to address this point once we will have https://github.com/aces/cbrain/issues/967 fix.

**Comment by prioux** [comment]
Just a) to be done, assigned to myself

**Comment by prioux** [comment]
Point e) is closed by #993

**Comment by prioux** [comment]
All done.
