### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - File upload and Storage location selection

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#958]
Received via direct email message sent to Diana:

a) Upload file:The name of the file I was trying to upload had invalid characters (it was: File 1 2020-05-25). So I had to rename it (File_1) and try again. 

b) I don’t understand this: SELECT STORAGE FOR FILE CONTENT
The storage configuration selected here will control who has access to the content of the file. Each storage configuration is associated with a particular project, and the members of that project are the ones who can access the file's content.

I choose NeuroHubStore randomly, but someone will have to explain to me.

**Comment by bryancaron** [comment]
a) no spaces allowed in file names, among other restrictions. documentation and training issue.

b) Default will be NeuroHubStore
- but needs to be set at account creation time
- right now not easily to differentiate between users applying though CBRAIN versus NeuroHub instance to get context (cumbersome!)

- can add an attribute where the form was filled from
- easy to implement 

- done after the code merge - few lines of code - estimate < 1 day after code merge

**Comment by prioux** [comment]
Let's make sure all users gets a default data provider configured at account creation, and depends on neurohub user vs cbrain user

**Comment by prioux** [comment]
This was fixed by #979, we simply need to be careful when creating new accounts to remember to assign the proper default DP.
