### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - user invitation and notification

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#959]
Received via direct email message sent to Diana:

a) Invite users: easy, I invited Diana, invitation is pending. I would like to receive a notification when the person ‘accept’ my invitation.

**Comment by MontrealSergiy** [comment]
NeuroHub does not have message support besides invites and flash. For now I add invitation acceptance message as requested, however I do not go into beatifying colors scheme, may be @candicecz can check styling latter.

**Comment by MontrealSergiy** [comment]
Adding / improving full cbrain messaging into neurohub possible, should go to different ticket.  There are some nuances - do we want distinguish neurohub and cbrain send message by color or otherwise etc.

**Comment by bryancaron** [comment]
Comment: worth implementing messaging system on the neurohub side.

Estimated work = 1 week (coding and style) ; 4 days person coding time

**Comment by MontrealSergiy** [comment]
was erroneously closed. Working on messaging system

**Comment by MontrealSergiy** [comment]
Is it ok to move messaging system into separate feature and submit bugfix for the problem ? Otherwise I will the most critiques would be for messaging system rather than bugfix itself

**Comment by MontrealSergiy** [comment]
As agreed with the team in the scope of this ticket only rudimentary elements of message system are implemented. Rest of messages and user to user communication are moved to another ticket.

**Comment by prioux** [comment]
Fixed by #990
