### ISSUE TITLE
Implement groups that are viewable yet not assignable

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#962]
I'm not sure we have this right now.

* If we flag a group as 'invisible', resources associated with the group can be accessed but not assigned to.
* However, in NeuroHub, the group will not be shown in the project list

I need a group to be visible in the project  list, yet not assignable. E.g. UK BioBank access project.

**Comment by bryancaron** [comment]
Merge is a pre-requisite step ; few hours after that
