### ISSUE TITLE
NeuroHub Alpha user feedback - welcome page : tell new users they can login w CBRAIN credential

### ISSUE THREAD

**Issue by christinerogers** [aces/cbrain#966]
Not a bug, but a suggestion: In the welcome page, indicate to new visitors that they can log in with a CBRAIN credential, instead of requesting a new account. 

Natacha responded to my new account request to tell me this info. 
This site is just different enough that it's not clear this is a skin on the main CBRAIN portal.

related to: #961
(Thanks Natacha for adding the right labels here, since I don't have that repo permission)

**Comment by natacha-beck** [comment]
Close by: #971
