### ISSUE TITLE
Swaggerhub data_providers​/{id}​/register API documentation typos/missing params

### ISSUE THREAD

**Issue by laemtl** [aces/cbrain#974]
On [swaggerhub](https://app.swaggerhub.com/apis/prioux/CBRAIN/5.1.3#/DataProviders/post_data_providers__id__register) > ​/data_providers​/{id}​/register > multi_registration_mod_req > model, the text makes multiple references to the unregister endpoint.
![Screenshot from 2020-07-29 11-05-25](https://user-images.githubusercontent.com/32041423/88817498-91808600-d18b-11ea-8365-e03e32e36c4b.png)

The documentation also specifies that 

> You can also specify to copy/move the files
> to another Data Provider after file registration.

but this is undocumented. Below is the list of undocumented params provided by @prioux. It can be nice to have them included in swaggerhub!

> {
> 	"auto_do"                => "MOVE",
> 	"other_data_provider_id" => "27", 
> 	"basenames"              => ["capture.png", "hello.txt"],
> 	"filetypes"              => ["ImageFile-capture.png", "TextFile-hello.txt"],
> 	"id"=>"51"
> }

**Comment by prioux** [comment]
Fixed in dev by https://github.com/aces/cbrain/commit/30b5c69fcc40fafc99daa4dbf601d2e2422e501e
