### ISSUE TITLE
First login to NH still not straightforward. 

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#991]
When login the first time in NH if a user have to reset their password, he will be: 
  - Redirected to the change your password CBRAIN page
  - Then to the licenses page of CBRAIN
  - Finally to the projects page of CBRAIN.

**Comment by prioux** [comment]
Closed by #993

**Comment by natacha-beck** [comment]
The merged #993 was functional. But today I tried to create a new user and to first login in NH and I get the same buggy behavior: 

> 
>     Redirected to the change your password CBRAIN page
>     Then to the licenses page of CBRAIN
>     Finally to the projects page of CBRAIN.
>

**Comment by prioux** [comment]
OK, it's a consequence of the fact our main CBRAIN install has site-wide licenses that the user must agree to. We didn't have any such licenses installed on our dev server.

I'll disabled the license checks for requests made to neurohub pages.

**Comment by prioux** [comment]
Fixed in https://github.com/aces/cbrain/commit/0aaa89426eeea2aef11b3b0c7f6f6e6d6f59870b

But I will open a new feature request: we need to handle nicely site-wide licenses on the NeuroHub side.
