### ISSUE TITLE
Add information in user new page + allow selection of preferred DP

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#992]
When creating a new account in CBRAIN we do not have information about the provenance of the request, was is send by CBRAIN or NH (even if we have the information in index signup page).

In the meantime, we can add a select box allowing the admin to select a `pref_data_provider_id` (note: this information is store in the metadata of the user.

**Comment by prioux** [comment]
I'm adding the NeuroHub tag because it will help provide a default DP for new NeuroHub users.

**Comment by prioux** [comment]
Implemented in #997
